### ISSUE TITLE
Avoid adding more auto-imported modules.

### ISSUE THREAD

**Issue by carljm** [andrewgodwin/channels#1]
Adding stuff to registries as an import-time side-effect of decorators is an anti-pattern. It impedes testability, and it causes behavior changes depending on which modules have been imported.

Django already contains this anti-pattern (for signals and for admin, and in even more convoluted fashion for models), and django-channels requires expanding it to even more modules in order to catch decorated consumers.

I think there are two better options:

1) Relying an decorators and import side effects for signal registration has been deprecated in favor of explicitly registering signal handlers in `AppConfig.ready`. The same technique could be recommended here (instead of using decorators).

2) If the convenience of a decorator is important, we could rely on the venusian package (http://venusian.readthedocs.org/en/latest/), which solves this problem. A venusian-based decorator doesn't have any side effects, all it does is annotate the decorated function with some metadata. Then you run a venusian "scan" at a well-defined point in your code, which walks the module tree and imports all modules, looking for functions which have been annotated with venusian metadata and running a callback on them. That callback can do whatever needs to be done (e.g. put the function in a registry). This avoids import-time side effects and changes in behavior depending on the timing of module imports. All modules are checked for decorated functions, and the scan happens at a clearly-defined point (which would fit in well with the new `django.setup()` in 1.7+). Venusian is a solid and battle-tested solution to this problem (all decorators in the Pyramid web framework use it).

**Comment by andrewgodwin** [comment]
I was somewhat hesistant to introduce another import-time-registration-pattern, but I figured since we already have them I could take the opportunity to rewrite it for all four things (admin, signals, models, consumers) to something slightly nicer, probably like a full module tree walk.

I don't want to encourage the AppConfig.ready() method, since I want the channel names to be right next to their consumers.

**Comment by nemesisdesign** [comment]
Refactoring all the 4 things could require quite some time though.
Are you thinking about refactoring all 4 together or in a gradual process?

**Comment by andrewgodwin** [comment]
Together - I'm of the opinion that moving autodiscovery to one place won't be too tough, but I'm going to look at it properly later on once I have this next lot of features done.

**Comment by nemesisdesign** [comment]
:+1:

**Comment by andrewgodwin** [comment]
After some thought, I moved channel consumers to a URLs-like pattern of single, centralised list, so there is no longer a need for autoimport - it's been removed.

**Comment by Gyan888** [comment]
I am using Channel rest API ,I am facing issue here whenever i try to make changes in table by admin pannel   i am getting push notification successfully however when i try to do same by queryset I am not getting proper Responses .
