### ISSUE TITLE
Older versions of Redis cause a bug

### ISSUE THREAD

**Issue by SIlver--** [andrewgodwin/channels#100]
I was using `redis 0.8.2` and I had an annoying issue I couldn't figure out until I upgraded to the latest version. After about 2-3 minutes the `onmessage` on the client side would stop listening (or at least stop being able to receive). `send` would still work, if I joined as a new client, I was able to see the old clients message but it was not able to see the new client's messages. Very strange bug to be noted, it should be at least stated in the docs that the latest version of redis should be ran.

**Comment by andrewgodwin** [comment]
Do you mean the python `redis` bindings or the `asgi_redis` package?

**Comment by SIlver--** [comment]
`asgi_redis`. And I was mistaken of the version number, after looking at my terminal history it was actually `asgi-redis 0.8.3 0.8.3`

**Comment by andrewgodwin** [comment]
Yes, the older ones were written against a different spec - I did put some notices out when I announced previous releases, but I'll do that doubly so for the 1.0 release (and maybe throw a check into Channels too if it sees the package around)
