### ISSUE TITLE
 NameError: name 'file' is not defined

### ISSUE THREAD

**Issue by RichardProsser** [andrewgodwin/channels#102]
Attempting to install 'channels' within PyCharm Community Edition 2016.1
Build #PC-145.260, built on March 22, 2016
JRE: 1.8.0_60-b27 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

Effective command: "pip install channels"

Collecting channels
  Using cached channels-0.10.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Django>=1.8 in c:\python34\lib\site-packages (from channels)
Collecting asgiref>=0.10 (from channels)
  Using cached asgiref-0.11.1-py2.py3-none-any.whl
Collecting daphne>=0.10 (from channels)
  Using cached daphne-0.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in c:\python34\lib\site-packages (from asgiref>=0.10->channels)
Collecting twisted>=15.5 (from daphne>=0.10->channels)
  Using cached Twisted-16.0.0.tar.bz2
Collecting autobahn>=0.12 (from daphne>=0.10->channels)
  Using cached autobahn-0.13.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\autobahn.egg-info
    writing pip-egg-info\autobahn.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\autobahn.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\autobahn.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\autobahn.egg-info\requires.txt
    writing manifest file 'pip-egg-info\autobahn.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    package init file 'twisted\plugins\__init__.py' not found (or not a regular file)
    reading manifest file 'pip-egg-info\autobahn.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\autobahn.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\TEMP\AppData\Local\Temp\pycharm-packaging\autobahn\setup.py", line 245, in <module>
        from twisted.internet import reactor
      File "C:\Python34\lib\site-packages\twisted\internet\reactor.py", line 38, in <module>
        from twisted.internet import default
      File "C:\Python34\lib\site-packages\twisted\internet\default.py", line 56, in <module>
        install = _getInstallFunction(platform)
      File "C:\Python34\lib\site-packages\twisted\internet\default.py", line 50, in _getInstallFunction
        from twisted.internet.selectreactor import install
      File "C:\Python34\lib\site-packages\twisted\internet\selectreactor.py", line 18, in <module>
        from twisted.internet import posixbase
      File "C:\Python34\lib\site-packages\twisted\internet\posixbase.py", line 23, in <module>
        from twisted.internet import error, udp, tcp
      File "C:\Python34\lib\site-packages\twisted\internet\udp.py", line 53, in <module>
        from twisted.internet import base, defer, address
      File "C:\Python34\lib\site-packages\twisted\internet\base.py", line 23, in <module>
        from twisted.internet import fdesc, main, error, abstract, defer, threads
      File "C:\Python34\lib\site-packages\twisted\internet\defer.py", line 29, in <module>
        from twisted.python import lockfile, failure
      File "C:\Python34\lib\site-packages\twisted\python\lockfile.py", line 52, in <module>
        _open = file
    NameError: name 'file' is not defined
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\TEMP\AppData\Local\Temp\pycharm-packaging\autobahn
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by andrewgodwin** [comment]
This looks like a fundamental problem with your Python install (`file` is a built in Python object). What version of Python are you using?

**Comment by andrewgodwin** [comment]
Oh, nevermind, `file` is gone in Python 3. Let me see if it's a Twisted bug?

**Comment by andrewgodwin** [comment]
This is an upstream Twisted bug with Python 3 on Windows: https://twistedmatrix.com/trac/ticket/7626

Closing this as there's not much I can do about it. I'll see if I can encourage them to fix it.
