### ISSUE TITLE
Group send fail !!!!

### ISSUE THREAD

**Issue by viphxin** [andrewgodwin/channels#105]
when I was open some browser tab to connected to websocket, and i send messages to each other  browser tab,it was going well. but some times ago, i continue to send messages to each other, it was failed. and i found server can receive messages but Group send fail!!!! and no error messages display

**Comment by viphxin** [comment]
I download the chatroom demo

**Comment by andrewgodwin** [comment]
Can you tell me what versions of `channels`, `asgiref`, `daphne` and `asgi_redis` you have please? If you don't have the latest versions, that may be why it's failing.

**Comment by viphxin** [comment]
channels in Group are auto removed. beacuse of expire out. I fixed it by set CHANNEL_LAYERS CONFIGS expiry to large number.In fact, I'm confused in this

**Comment by andrewgodwin** [comment]
Group expiry in the most recent versions is set to `86400` seconds (one day). It sounds like you have an older version of the `asgi_redis` package; update it to `0.10.0`.

**Comment by viphxin** [comment]
ths
