### ISSUE TITLE
Possible to combine gunicorn with channels?

### ISSUE THREAD

**Issue by Windsooon** [andrewgodwin/channels#108]
I had seen the doc about Running ASGI under WSGI, so how to set up gunicorn when I'm running channels?

**Comment by andrewgodwin** [comment]
Just use the wsgi.py file that's shown in the docs and point gunicorn at it like you would any other Django deploy, then run a worker with `manage.py runworker`

Be warned, though, that this will not let you use WebSockets, only the background task part.

**Comment by andrewgodwin** [comment]
This is from the Channels 1 days, so its very old. That said, if you only run gunicorn, you won't get any async benefits at all.
