### ISSUE TITLE
Daphne access logs

### ISSUE THREAD

**Issue by sachinrekhi** [andrewgodwin/channels#110]
Prior to moving to django-channels, I used gunicorn in production and configured it to log an access log file. I'm trying to figure out now that I've moved to daphne in production how to accomplish the same thing.

Based on the suggestion in the docs, I've setup supervisord, expecting the redirected stdout and stderr log files would have the access logs. However the resulting daphne.log file is empty. I thought I might have to configure daphne's verbosity, but it seems like the default daphne verbosity is INFO level, but still am not getting any access logs.

Is it wrong for me to expect the access logs from daphne's redirected output? Or am I just configuring it wrong?

My supervisord is configured as the following:

```
[program:channel_worker]
command=python manage.py runworker
process_name=channel_worker_%(process_num)s
numprocs=3
priority=2
autostart=true
autorestart=unexpected
stdout_logfile=/home/webuser/helloworld/notejoy/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=0 
redirect_stderr=true

[program:daphne]
command=daphne -b 127.0.0.1 -p 9000 notejoy.asgi:channel_layer
process_name=daphne
numprocs=1
priority=3
autostart=true
autorestart=unexpected
stdout_logfile=/home/webuser/helloworld/notejoy/logs/daphne.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=0 
redirect_stderr=true
```

**Comment by andrewgodwin** [comment]
Daphne actually doesn't have access logs right now, but you're right to expect them (there's a way to plug in logging configuration to it that `runserver` uses to show a similar kind of output).

Need to also work out what format to use for those logs; something close to NCSA, probably, but with a few things changed around to log WebSocket activity.

What would you like to see in the way of WebSocket logging? Connects/disconnects? Paths? Remote addresses?

**Comment by sachinrekhi** [comment]
Oh got it. I assumed daphne had them since when I use runserver locally I get pretty much what I'm expecting when I see something like below. But sounds like this is the logging configuration that you mentioned exists specifically for runserver but not daphne yet.

```
[2016/03/30 22:27:20] HTTP GET /reduce-15b 200 [0.08, 127.0.0.1:59404]
[2016/03/30 22:27:21] HTTP GET /api/1.0/notifications/count 200 [0.08, 127.0.0.1:59409]
```

I'll just rely on nginx access logs for now (which I have setup as a reverse proxy in-front of daphne for both http & web socket traffic).

Something along the lines of NCSA format is exactly what I'm looking for and would satisfy my requirements.

In terms of websocket, I'll like to see connect/disconnect with path and remote address. I actually would like message received as well, though I can imagine others may think that could get too chatty for chatty socket communication scenarios. In my case it wouldn't be too chatty and I actually have a logger outputting this anyway in my own socket consumers for debugging and general logging. I also have message sent in my own consumer logging, though might be a bit much for generic access log...

**Comment by andrewgodwin** [comment]
Okay, access logs are in daphne `0.10.2`, out now. Stdout by default, use `--access-log` to point them somewhere else.

It only does websocket connect/disconnect and HTTP request completion; getting websocket packets received would involve too much overhead for my liking to check the hooks even if the logging path wasn't enabled.

You can also do `manage.py runworker -v 2` if you want to see each consumer being run and what channel it's being run from. That might help with some additional debugging.

**Comment by carltongibson** [comment]
Sorry to ping an old issue but this looked like the closest hit...

Could you point to where the logging format is set — I want to add the response time to that for something like: 

    127.0.0.1:48108 - - [10/May/2017:12:42:53] "GET /docs/" 200 422083 <RESPONSE_TIME_HERE>

**Comment by andrewgodwin** [comment]
The current format is fixed in the `AccessLogGenerator` here: https://github.com/django/daphne/blob/a59bd123a919f167ce69836bcac1e657a8cb8b8f/daphne/access.py#L58

The `time_taken` is passed into the access log generator as part of the event details (for `HTTP complete` events only, of course), so you could do your own subclass to provide this, but there is no easy way of using the Daphne CLI code while also providing your own access log classes.

**Comment by carltongibson** [comment]
@andrewgodwin OK Thanks for the details. I'll have a think about it and come back to you (perhaps in a new issue). 👍
