### ISSUE TITLE
Allow configuration of what channels workers listen on

### ISSUE THREAD

**Issue by andrewgodwin** [andrewgodwin/channels#116]
Suggested that it's an argument to `runworker` where the user can provide multiple arguments, or a glob string that's expanded against the available set.

**Comment by titusz** [comment]
This seems quite important, if there are ANY consumers that have long running tasks (lets say some minutes or even hours). Once you have more of those tasks than running worker instances/processes wouldn´t it completely kill the frontend?

**Comment by andrewgodwin** [comment]
Yes, that's correct, though generally putting long-running things in Channels should be discouraged, I should update the docs to reflect that. I plan to get this in soon.

**Comment by titusz** [comment]
The first senteces of the documentation (In Short) say:

- Background tasks, running in the same servers as the rest of Django

Are you planning to document that its not supported or is worker/channel selection generally on the roadmap?

**Comment by andrewgodwin** [comment]
They are supported, just only on the order of seconds in the current configuration. Channel restrictions for `runworker` are incoming.

**Comment by andrewgodwin** [comment]
`runworker` now has `--only-channels` and `--exclude-channels` options, e.g.:

    `python manage.py runworker --only-channels=http.* --only-channels=websocket.*`
