### ISSUE TITLE
Allowing HTTP sessions on websocket.receive

### ISSUE THREAD

**Issue by screx** [andrewgodwin/channels#117]
Hi Andrew,

Is there a way to enable the channel_session_user_from_http decorator onto the websocket receive consumer? For my implementation I wanted to pass any changes in my parameters through the websocket to update the data stream in real time and I can't get the request data to do so

Thanks!

**Comment by andrewgodwin** [comment]
The cookie data that it needs is only in the `websocket.connect` channel, so you put the decorator onto a consumer there and simply use `channel_session_user` on your `receive` consumer.

(The decorator copies the auth data into the channel session so any other websocket consumers that aren't `connect` can access it; that's the difference between `channel_session_user_from_http` and `http_session_user` decorators, in fact; both of them extract the user from the HTTP session, but the first then copies the data into the channel session so `channel_session_user` can see it).
