### ISSUE TITLE
websocket.ws_receive is called before websocket.ws_connect

### ISSUE THREAD

**Issue by darklow** [andrewgodwin/channels#120]
In specific case `websocket.ws_receive` is called before `websocket.ws_connect`.
In normal scenario everythings works fine.
But if on the client side I use automatic reconnection onclose and as soon as websocket is connected again send message immediately then in Django i got both calls in reversed order `ws_receive` first, in which case I cannot get authorized user anymore.

It easy to test if i restart Django runserver while client is connected, then connection from client side is lost and as soon as connection is established i see following in my console:
```
Channel layer default (asgi_redis.RedisChannelLayer)
Quit the server with CONTROL-C.

[2016/04/06 06:27:48] WebSocket CONNECT /forum/ [127.0.0.1:49565]
WS_RECEIVE:  2016-04-06 11:27:48.194518+00:00 AnonymousUser       <<< This comes first and without user
WS_CONNECT:  2016-04-06 11:27:48.201150+00:00 Kaspars Sprogis
[2016/04/06 06:27:48] WebSocket CONNECT /forum/ [127.0.0.1:49570]
WS_CONNECT:  2016-04-06 11:27:48.362870+00:00 Kaspars Sprogis
```

This is my `consumers.py`:
```py

from channels.auth import channel_session_user, channel_session_user_from_http

@channel_session_user_from_http
def ws_connect(message):
    print 'WS_CONNECT: ', now(), message.user

@channel_session_user
def ws_receive(message):
    print 'WS_RECEIVE: ', now(), message.user

```

Any ideas how to resolve this or why this happens?

Seeing duplicate /connect/ event is also interesting, however on client/JS side all events happen in correct order.
```
waiting...
waiting...
onOpen / socket.readyState = 1
sending message...
```
Thank you.

**Comment by sachinrekhi** [comment]
You need to use the enforce_ordering decorator to prevent this, as described here: https://channels.readthedocs.org/en/latest/getting-started.html#enforcing-ordering

**Comment by darklow** [comment]
`@enforce_ordering` saved my problem.
Thank you!
