### ISSUE TITLE
AttributeError: 'AsgiRequest' object has no attribute '_read_started'

### ISSUE THREAD

**Issue by michaelkuty** [andrewgodwin/channels#123]
if len(request.FILES) == 1:
	  File "/srv/leonardo/sites/csb/local/lib/python2.7/site-packages/channels/handler.py", line 152, in _ge
	t_files
	    self._load_post_and_files()
	  File "/srv/leonardo/sites/csb/local/lib/python2.7/site-packages/django/http/request.py", line 249, in 
	_load_post_and_files
	    if self._read_started and not hasattr(self, '_body'):
	AttributeError: 'AsgiRequest' object has no attribute '_read_started'

**Comment by michaelkuty** [comment]
Proposed fix in #124

**Comment by andrewgodwin** [comment]
Fixed.

**Comment by Suryaphalle** [comment]
AttributeError at /accounts/login/
'AsgiRequest' object has no attribute 'session' ??
need help with it

**Comment by proofit404** [comment]
@Suryaphalle Please provide whole traceback and project configuration in the separate issue.
