### ISSUE TITLE
Group.send(exclude=reply_channel)

### ISSUE THREAD

**Issue by sachinrekhi** [andrewgodwin/channels#125]
I'm trying to implement the following scenario: A user edited a document and that edit needs to now be sent to everyone else. My goal was to leverage a Channel Group to accomplish this. When a user views a document, they are added to a Group keyed off of the document id. And then when someone edits, I use Group.send to send the edit to all others on the channel. However, this approach also sends the message back to the person who edited the note. I'm trying to make it so I can EXCLUDE the person who made the edit from receiving the broadcast.

One thought was if we changed the signature to **Group.send(self, content, exclude=None)**, allowing an optional exclude parameter which can take a **reply_channel** to exclude. This way I can still get all the benefits of Group handling expiry, etc. but safely just exclude a specific person. No guarantees have to be made about whether the reply_channel is even in the group, just to ensure it is not actually sent to that specific channel for this one message (like a one-time discard).

I was hoping that you might tell me this scenario is less costly to support as it would make my life easier. Without this, it seems I would need to either ensure the client ignores the message (probably the easiest solution, though extra traffic) or use my own mechanism for managing who is currently viewing the doc outside of a group (my thought was to still use a Group for each individual connection and keep track of those groups in a separate redis list so that way I get expiry support but can manage the group myself).

Thoughts?

**Comment by andrewgodwin** [comment]
It would be expensive to include an `exclude` parameter unfortunately, in the sense that you suddenly have even more logic to do and data to send around, and I don't think it's worth adding this to a core API that everything has to support.

However, in your situation, I can think of two way to solve this:

- Send the message to your client socket anyway, and just have it filter it out upon receipt. This makes your server code simpler and moves the processing to the client computers, which is more scalable.

- Manually do the fan-out yourself by re-implementing the group system, which isn't too hard to do.

I'd recommend just sending the message to the author's client anyway and just having a client ID in there that a client can use to filter out messages coming from itself.

**Comment by sachinrekhi** [comment]
I'm planning on using the reply channel name as a unique client ID as opposed to generating a separate id. That should work fine right, given reply channel names are unique to each connected websocket? I'll just have the client store it on initial connection and then filter out messages sent to it with it.

**Comment by andrewgodwin** [comment]
Yes, reply channel can be used as a unique socket identifier for WebSockers, and in fact it's enocouraged to do so.

**Comment by sebhaase** [comment]
please point to the respective source where one would `Manually do the fan-out yourself by re-implementing the group system, which isn't too hard to do.`

I think this `exclude` option has some advantages over doing it client-side -- especially when response time is not most critical and client-complexity is more of a concern ...

**Comment by sebhaase** [comment]
should this ticket be reopen - I just asked for some more detail on an ealier comment ....

**Comment by andrewgodwin** [comment]
I just missed that comment. It does not need to be re-opened, I still disagree it should be added as it would break most of the efficiencies of groups.

What I meant was that you are free to manually add and remove reply channel names from some other datastore (relational database, redis, etc.) on connect/disconnect, and then you have a version of groups that you can customise yourself.

**Comment by sebhaase** [comment]
Thanks for the reply. I would like to add an additional method for groups called something like `Group.send_except()`.   This is my understand from what you said in your first comment (Apr 9,2016): "... re-implementing the group system, which isn't too hard to do."
So, my question: can you point to the place in the source tree where one would have to make such adjustments ...
(BTW, I really don't understand why adding this "except" logic in a separate function (or even in an `if` condition as optional argument to `Group.send`) would slow down the normal use case  ...     If I knew the respective sections in the source I maybe could follow your argument better)
Thanks, -S.

**Comment by andrewgodwin** [comment]
The group sending logic is implemented in Lua on the various Redis shards for efficiency reasons. In order to make it exclude certain channels, the group names would need to be transported over to the server as additional arguments so the script can exclude them (it also means you can't pass python code in to execute as an if condition)

That's just the Redis backend; the point of having a small API is that it allows more flexibility for other backends to do what they want (e.g. the WIP RabbitMQ backend does all this using exchanges and I believe those are even harder to exclude on a conditional basis). This means adding just that one endpoint means loads of work and possibly reducing the performance of every backend that had optimised not to have to exclude messages.

Plus, the design of groups means that there's already a way to selectively not send to part of a group, and that is to have two groups for the two sets of people and swap in which ones you send (and this is the intended design, and what things are optimised for).

For these reasons, I am currently a hard veto on adding this to the core channels Group system, and I would reject any pull requests that added it in.

**Comment by proofit404** [comment]
Hello,

Groups are implemented in the RabbitMQ layer using exchange to exchange bindings. I guess it is possible to set tricky combination of exchange type and message headers to remove some queues from routing. But I should test it first. Also my main goal is to be fully compatible with ASGI spec. So as far as this veto decision stays actual I wont implement this feature in the asgi_rabbitmq.

Regards, Artem.

**Comment by josezy** [comment]
I did [this](https://stackoverflow.com/a/57035230/4526240):
```python
async def websocket_receive(self, event):
    encoded_frame = event.get('text', None)
    if encoded_frame is not None:
        await self.channel_layer.group_send(
            self.flight_room,
            {
                'type': 'video_frame',
                'frame': encoded_frame,
                'sender_channel_name': self.channel_name
            }
        )

async def video_frame(self, event):
    if self.channel_name != event.get('sender_channel_name'):
        await self.send({
            'type': 'websocket.send',
            'text': event.get('frame')
        })
```
Helped when I want to send images because eliminates an unnecessary sending call

**Comment by abedyngash** [comment]
@josezy What if I wanted to do the group send outside the consumer? How do I access the channel name?

**Comment by josezy** [comment]
> @josezy What if I wanted to do the group send outside the consumer? How do I access the channel name?

You gotta know who you want to send or not the message, `channel_name` is used here because we are in the consumer context, in you case (outside the consumer) who is the sender? do the sender has a channel? once you know the sender you could figure out a way to filter it from the group
