### ISSUE TITLE
Running multiple workers with runserver

### ISSUE THREAD

**Issue by sachinrekhi** [andrewgodwin/channels#128]
I'm using runserver in development (since I get the auto-reload on code changes). However, I'm starting to see the following error in the logs:

```
worker - Exceeded number of retries for message on channel websocket.disconnect: {u'path': '/', u'__retries__': 11, u'order': 4, u'reply_channel': u'websocket.send!lSuKAngbDfik'}
```

Is there a way to run multiple workers with runserver? This way I can still get the benefits of auto-reload for development productivity, but not have these limitations of overloading the single worker (which wouldn't happen in production given more workers)?

**Comment by andrewgodwin** [comment]
runserver already runs four worker threads - you should never see retry errors like this. Are you using the enforce_ordering decorator? If you do that wrong (i.e. on receive but not connect) this sort of thing happens.

If you do want to run more workers, just use `manage.py runworker` in a second terminal to start another one.

**Comment by sachinrekhi** [comment]
Below is my only consumers code entrypoint. This is the right way to use the enforce_ordering decorator, correct?

```
from channels.sessions import enforce_ordering
from channels.auth import channel_session_user_from_http, channel_session_user

from notes.api.socket import SocketRouter

@enforce_ordering
@channel_session_user_from_http
def connect(message):
	SocketRouter().connect(message.channel_session, message.reply_channel, message.user)

@enforce_ordering
@channel_session_user
def disconnect(message):
	SocketRouter().disconnect(message.channel_session, message.reply_channel, message.user)

@enforce_ordering
@channel_session_user
def message(message):
    SocketRouter().message(message.channel_session, message.reply_channel, message.user, message.content)
```

My guess is that when I was originally sending every keystroke from the client to the server in my collab edit scenario, it was overloading the 4 channel workers. Since batching a few seconds worth of edits before sending to server, the exceeded retries errors seem to have gone away.

**Comment by andrewgodwin** [comment]
Yes, that sort of very chatty communication would do it; Channels can only push around 100 messages/second through the normal backend on a normal single machine setup. Batching sounds sensible, but you can always run more workers too (though in this case less workers may have been better as it would process more in order)

**Comment by sachinrekhi** [comment]
Thanks for the performance data. Do you have a sense of what kind of roundtrip time is realistic for a normal backend w/ normal single machine setup? Say for like an simple echo message where client sends echo websocket message and server immediately echoes it back to client.

**Comment by andrewgodwin** [comment]
There's some initial benchmark data here, including median and 95th percentile latencies for normal and under-strain single-machine setups: https://gist.github.com/andrewgodwin/8b684be1e0b5d663e04d - in the situation you're talking about,  it was a 12ms median latency.
