### ISSUE TITLE
Class-based Consumers

### ISSUE THREAD

**Issue by sachinrekhi** [andrewgodwin/channels#131]
I was excited when Django introduced class-based views since it created a far more natural way to organize associated code into classes.

When I look at the experience for writing channel consumers today, it seems like we are back to using plain functions instead of a class-based approach.

In my own channels code I've created a class-based consumers approach with a few shim classes. With these shims I'm able to write something like the following:

```
class Connect(SocketAPI):
	def connect(self, user):
		# add reply channel to user group channel
		Group('user:%s' % user.id).add(self.reply_channel)

class Disconnect(SocketAPI):
	def disconnect(self, user):	
		# remove reply channel from user group channel
		Group('user:%s' % user.id).discard(self.reply_channel)

class ViewDocument(SocketAPI):
	def message(self, user, message):
		# process message with type=VIEW_DOCUMENT
		document_id = message['document_id']
		# etc
```

While this approach certainly isn't generic enough for django channels core, thought I'd just throw out the idea. It may be an interesting approach for third-party django channel apps to enable similar shims to allow such an approach specifically for say websockets. Or just like how the Views abstraction is now just a simplification on top of raw django channels, maybe there is room for a SocketMessage simplification on top of django channels as well.

**Comment by andrewgodwin** [comment]
Yes, I've specifically  called out wanting class-based consumers in two talks now - I just haven't got to it yet, and I'm hoping it's something we can get contributed by someone else. Specifically, a consumer for easy websocket handling with sessions and optionally json encoding.

**Comment by awwester** [comment]
@andrewgodwin are changes like this something that would be contributed to this package, or into the django 1.10 integration?

**Comment by sachinrekhi** [comment]
Awesome. Talks online by any chance?

**Comment by AlexejStukov** [comment]
I have also tried to write my own version of class-based [consumers](https://github.com/AlexejStukov/channels/blob/master/channels/consumers.py) based on the routers of [swampdragon](https://github.com/jonashagstedt/swampdragon), but I don't know if this approach fits channels.

Step 1 is that the user can subclass ``Consumer`` or ``GroupConsumer``, add his own methods to ``valid_calls`` and use a predefined javascript function to call that method. The question here is if  ``receive`` should parse the message or if that should be left to the user. 

Step 2 is to add further integration with Django's models:
The ``ModelConsumer`` and ``ModelInstanceConsumer`` are there for this. They should provide standard calls like get an instance of this model by ``pk`` or the value of a field by name and send updates, deletes, etc. to the connected channels. But I'm not shure yet, how the consumers should be connected to the models? By the django signals or by a mixin?

**Comment by andrewgodwin** [comment]
I'd ideally like to see them as a third-party package that works with both Channels external and internal, but I might include a base view and JSON view example into Channels to solve the very common case and provide a base pattern others can work off of.

The basic design I was thinking was:
- A very base websocket class that provides connect, receive and disconnect overrideable methods, a send method, and a single entrypoint you can include() into the routing (it's possible for anything to provide a routable interface). The reply channel would be stored in self, so that send just took the text to send.
- A subclass of that which provides JSON encoding and decoding in send and receive

**Comment by Krukov** [comment]
@andrewgodwin I have tried to create my vision of CB Consumers, inspired by django CBV and django-rest-framework ViewSets - https://github.com/Krukov/cbchennels/blob/master/cbchannels/base.py . Is it close to what you wrote about? 
Also at repo you can see an example (it is rewriting instance of your multichat expample https://github.com/andrewgodwin/channels-examples/tree/master/multichat)

**Comment by andrewgodwin** [comment]
@Krukov My initial reaction is that it seems a little bit over-engineered but generally the right direction - do you have any examples of how it's used? I think getting the end-user API right is quite important, so I'd rather that's spot on, allowing internals to be changed later if needed.

**Comment by Krukov** [comment]
You can see example of consumers [here](https://github.com/Krukov/cbchennels/blob/master/examples/multichat/chat/consumers.py) and of routes [here](https://github.com/Krukov/cbchennels/blob/master/examples/multichat/chat/routing.py).
Yeah, I understand what you mean, I will hide/remove the excess API.

**Comment by KhasanovBI** [comment]
Something analogical, my decisions [here](https://github.com/KhasanovBI/rest_channels/blob/master/rest_channels/views.py).
[routing.py](https://github.com/YetAnotherTeam/jatumba-backend/blob/master/TPD/routing.py)
Example of old methods: 
[Only CBV](https://github.com/YetAnotherTeam/jatumba-backend/blob/c6462048014454b3aef669bbc622d93777252dd7/api/socket/views.py)
Example of new version specifying by nested routing:
[CBV with nested routing](https://github.com/YetAnotherTeam/jatumba-backend/blob/master/api/socket/views.py)

**Comment by andrewgodwin** [comment]
Just to check in on this again - for something to integrate into channels directly, I'm looking for something *very* thin, as in just a framework with send/receive/connect/disconnect methods, a subclass that does JSON encoding, and maybe another one that handles joining and leaving a set of channels as the socket connects and disconnects, but with anything excess trimmed off (I want to leave advanced sets of generic consumers to other packages, and just set a simple example).

Krukov, you have something that could be trimmed down for sure - are you still working on this, or I can take a shot at it if you want (I have some time to do it and I'd like to update some of the tutorial examples a bit)

**Comment by Krukov** [comment]
@andrewgodwin I already made some changes to make api/code more pure, in my view and now I working at subclasses. But It would great  if you'll take a shot. I am sure that you have  more clear view at how it should be implemented.

**Comment by ZuSe** [comment]
Any news on that?
I have worked with swampdragon over the last year and got very used to it's routers. Would be nice to have kinda the same functionality in channels. Also the idea of the SelfPublishModel is great, just don't know if it wouldn't be out of the scope of a thin framework...

**Comment by andrewgodwin** [comment]
I'm going to take a look at this over the next week or two - Swampdragon's higher-level router abstraction is something that I'd rather they or another project implement over channels, the goal here is more to just encapsulate JSON and WebSocket handling in a nice way and set an example for other class-based consumers to follow.

**Comment by andrewgodwin** [comment]
Now implemented: http://channels.readthedocs.io/en/latest/generics.html
