### ISSUE TITLE
Best approach to private chat

### ISSUE THREAD

**Issue by exp0nge** [andrewgodwin/channels#132]
Hello, I was wondering what the best methodology would be to creating private chat rooms. Should I use a `to` field with the rest of the message body or have routing with unique URLs? The purpose of my use of Channels is just for private chatting/messaging where the client only has access to one chat room while the provider has access to many client chat rooms.

Another approach I was thinking of using a Django model which is associated with every user so a client has a foreign key to a provider and their messages are routed that way. However, I think a more robust/generic method may be better?

**Comment by andrewgodwin** [comment]
I would go for unique URLs for each chatroom, unless you want to route more than one chatroom down the same chatroom (see my multichat example in https://github.com/andrewgodwin/channels-examples).

Definitely check authentication on the client side, though, you don't just want the url to provide access (unless you make the secret part of the URL long enough that it's unguessable, say 64 characters)
