### ISSUE TITLE
Django can't load static files with + symbol in them

### ISSUE THREAD

**Issue by darklow** [andrewgodwin/channels#136]
After fixing https://github.com/andrewgodwin/channels/issues/135 a new bug appeared.
Django can't load static files with `+` symbol in them, for example I have following file: 
`riot+compiler.js`

Now Django shows it as Not Found.
`http://localhost:8000/static/js/vendor/riot+compiler.js`

Before #135 fix it was working fine and if i remove `channels` it also finds the file.

**Comment by andrewgodwin** [comment]
I incorrectly used `unquote_plus` rather than `unquote` on the URL path, so it was seeing the `+` as a space. Fixed in daphne `0.11.3`.
