### ISSUE TITLE
Inconsistent bytes/string in request path

### ISSUE THREAD

**Issue by orf** [andrewgodwin/channels#137]
Hey, I'm experimenting adding channels to my app by adding a basic chat room. The code I have is pretty simple:

```python
def ws_connect(message):
    room = message['path']
    Group("chat" + room).add(message.reply_channel)


def ws_receive(message):
    data = json.loads(message['text'])
    room_label, text, user = data['room'], data['text'], data['user']
    Group("chat" + room_label).send({'text': text})


def ws_disconnect(message):
    room = message['path']
    Group("chat" + room).discard(message.reply_channel)
```

However on my system `message["path"]` is a string inside `ws_connect` but bytes inside `ws_disconnect`. For my co-worker it is always `bytes`.

What could be causing this? We are using the standard `asgi_redis.RedisChannelLayer` and not doing anything funky that I can see.

**Comment by andrewgodwin** [comment]
My apologies, it was a missed set of fixes in the new Daphne release. If you upgrade to daphne `0.11.2` all URL paths should now be url-decoded unicode.
