### ISSUE TITLE
Can't connect to WebSocket - Gives me 404 not found for /app1/votes/notification

### ISSUE THREAD

**Issue by asifpy** [andrewgodwin/channels#139]
I implemented channels examples here : 
https://github.com/asifpy/channels-examples

Everything works fine on my local server, but when I deployed on heroku it keeps returning 404. 

Here is the actual error: 

`WebSocket connection to 'ws://channels-examples.herokuapp.com/app1/votes/notification/ failed: Error during WebSocket handshake: Unexpected response code: 404`

Has anyone encountered the issue before or can point me in a starting direction of what might be causing this?

**Comment by andrewgodwin** [comment]
I'm afraid I can't specifically help with Heroku issues - did you correctly deploy it? You can't just use the standard Django buildpack. See Jacob's article for more: https://blog.heroku.com/archives/2016/3/17/in_deep_with_django_channels_the_future_of_real_time_apps_in_django

**Comment by ixser** [comment]
have you work it out ? i get the same problem now, i tried a long time but can;t work it out

**Comment by hatranductai** [comment]
I have the same problem too
