### ISSUE TITLE
Worker servers stalling up to 1 min in production

### ISSUE THREAD

**Issue by sachinrekhi** [andrewgodwin/channels#145]
I'm experiencing a strange issue running daphne / worker servers on a production AWS instance whereby the worker servers stop processing any incoming websocket requests for up to 1 minute. In most cases after that stall, everything starts up again and process the incoming messages appropriately, but there is that stall for up to a full minute. I've experienced this ~5 times in the last few days and it can be re-produced with enough requests sent to the server.

The issue can be reproduced even when there is only one client making web socket requests at a rate of 1 sent message per second.

I suspect the issue may be in the worker servers as opposed to my consumer code for the following reasons:
- when inspecting the client I can see initially websocket messages being sent to the server and acknowledged regularly by the server
- then all of a sudden I see 4-5 messages sent to the server that are not receiving acknowledgements
- my channel consumers are written in such a way to output a log message at the very beginning of their execution and again at the end of the execution. they also are surrounded by a @log_time decorator that outputs the elapsed time from beginning and end of processing. what I notice is that when the stall happens my logs show that it finished processing a message and that it doesn't receive a new message to process for that minute stall. similarly, when the stall ends and I see the elapsed time for processing each of those no-longer stalled messages, they are on the order of 10s of milliseconds, nothing close to the one minute stall, suggesting the stall was not in my consumer code, but before the messages were even sent to the consuers
- when looking at top during the actual stall, I notice that 2 worker servers are at the top of the CPU list at the exact same time as the stall. They remain there until slightly after the stall clears. You can see the top results captured here: http://cl.ly/1T0F0v3q3e0b

One of the times this occurred, I saw the following error in my nginx server log:
```
2016/05/02 10:20:03 [error] 2893#0: *98143 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 108.68.105.11, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/"
```

A couple of thoughts:
- Could the workers be getting into some kind of contention trying to pull messages from the channel layer?
- Could memory on the box be an issue? I only have 65MB of memory free, though 900MB of unused swap, so doesn't seem like it should create an issue

**EC2 Instance Setup**
- nginx as reverse proxy in-front of daphne
- 3 worker servers running
- redis channel layer
- nginx, daphne, worker servers, and redis all running on same EC2 instance
- m1.small EC2 instance type

**Comment by andrewgodwin** [comment]
Hmm, curious - could be any number of things. If it's semi-reproduceable, could you run the workers in verbose mode (`-v 2`) and see what they're doing when the stall happens? Verbose mode should print out every consumer being run as it gets run, so it might help trace it down to a particular decorator or code path.

**Comment by sachinrekhi** [comment]
Thanks for the debugging tip, will give this a try

**Comment by sachinrekhi** [comment]
OK I ran in verbose-mode and was able to re-create the stall, this time lasting 1 min 11 seconds before sending any socket messages back to the client.

Here is the top results at time of stall: http://cl.ly/2F0O110c0h2F
- this time all 3 worker servers seem to be busy leveraging cpu
- surprisingly high cpu steal % (17.3%st). could the issue just be aws is giving away cpu cycles to other VMs on the box? still high overall idle though (73%id) so not sure if that could really be the issue

Here is the verbose output for each of the 3 workers during the stall:
- http://cl.ly/2M1n2t32180A
- http://cl.ly/083n0X3P3Z0Y
- http://cl.ly/3x1a242R2J3L

The workers also look like they have not yet received a message to process yet given that the end of each of these outputs is my own consumer logging for a finished task and you don't see a "Worker got message on websocket.receive" output from the worker.

The odd thing is after the 1 min 11 seconds go by and I see the worker logs start to output again, they show that they receive the next message only 4 seconds after the previous message yet 1 min has actually passed before this message got outputted. (worker 1 output after, notice order=470 received 4 seconds after order=467 finished, which is where it stalled: http://cl.ly/2h2w2u2e3V1k)

I think my best guesses at this point are:
- daphne failing to send incoming message onto the channel layer (is there verbose settings for daphne telling me when it receives a message or puts a message on the channel layer?)
- issue with the workers pulling messages off of redis channel layer
- some slowdown / stalling issue with the VM / os itself

Any ideas?

**Comment by sachinrekhi** [comment]
So I migrated to a larger EC2 instance and these stalls are all gone. So looks like the issue was related to the EC2 instance and nothing with django channels / daphne / etc.

**Comment by andrewgodwin** [comment]
Thanks for investigating this - those small instances are famous for bad neighbours, so I'm not surprised, but it's weird it stalled for a whole minute. Were they going through a redis on the same box too?

**Comment by sachinrekhi** [comment]
Ya redis was on the same box too alongside memcache. Whole front end stack was on the same box but a separate server for MySQL.

Btw it looks like the way daphne runs its always using a consistent 10% CPU on the new box even with no incoming requests. Not an issue, but just curious, sounds like it is running in a loop of its own? Has very different cpu load than say nginx.

**Comment by andrewgodwin** [comment]
Yeah, currently it runs in a semi-idle polling loop internally rather than going full idle, as we haven't got Twisted support into asgi_redis yet. It'll get there, but for now it idles a little warm (doesn't affect performance under load though)

**Comment by abotte** [comment]
This topic shows up on top when googling for `connection reset by peer django channels`.
For those guys: make sure, that you send `{"accept": True}" in reply
