### ISSUE TITLE
Why not using Django caches

### ISSUE THREAD

**Issue by onegreyonewhite** [andrewgodwin/channels#150]
Hi
I am trying to use channels in your project.
I can not figure out how to describe the class for Backend ASGI. One question worries me:
Why not use caches in for backend? I am trying to describe the class, which would use a built-in caches, but I can not understand.
Can you help me with it?

PS: Sorry for my terrible English.

**Comment by andrewgodwin** [comment]
An ASGI backend requires a certain set of distributed operations - in particular, the ability to get the next message off the top of a channel on only one client, which is not something you can do with a general key-value store like a cache.

**Comment by onegreyonewhite** [comment]
Can you help me find, what is wrong with this code?

I tryed to use inmemmory, because ChannelLayer use dict, but something went wrong and this code doesn`t work. Nothing hepends.


    from asgiref.inmemory import ChannelLayer
    from django.core.cache import caches

    #################################################
    # DJANGO CACHE BACKEND
    #################################################
    try: 
        CACHE = caches['channels']
        PREFIX = ""
    except: 
        CACHE = caches['default']
        PREFIX = "channels-"

    class CacheDict(dict):
        def __init__(self, id,*args, **kwargs):
            super(CacheDict, self).__init__(*args, **kwargs)
            self.__cache__ = CACHE
            self.__prefix__ = PREFIX+id+"-"
            keys = self.__cache__.get(self.__prefix__+"keys")
            if keys is None: self.__cache__.set(self.__prefix__+"keys",[ ],10**10)
        
        def __append_key__(self, key):
            keys = self.keys()
            if key not in keys: 
                keys.append(key)
                self.__cache__.set(self.__prefix__+"keys", keys, 10**10)
        
        def __remove_key__(self, key):
            keys = self.keys()
            if key in keys: 
                keys.remove(key)
                self.__cache__.set(self.__prefix__+"keys", keys, 10**10)
        
        def __setitem__(self, key, item):
            self.__append_key__(key)
            self.__cache__.set(self.__prefix__+key, item)

        def __getitem__(self, key): 
            return self.__cache__.get(self.__prefix__+key)

        def __delitem__(self, key):
            self.__remove_key__(key)
            return self.__cache__.delete(self.__prefix__+key)
        
        def keys(self):
            return self.__cache__.get(self.__prefix__+"keys")
        
        def get(self, key, default=None):
            return self[key] or default
        
        def setdefault(self, key, default=None):
            result = self.__cache__.get(self.__prefix__+key)
            if result is not None: return result
            else:
                self[key] = default
                return default

        def clear(self):
            for key in self.keys(): self.__delitem__(key) 

        def has_key(self, k):
            return self.__cache__.has_key(self.__prefix__+k)
        
        def items(self):
            [ self.__remove_key__(key) for key in self.keys() if not self.get(key) ]
            return [(key, self.get(key)) for key in self.keys() if self.get(key) ]
        
        def values(self):
            [ self.__remove_key__(key) for key in self.keys() if not self.get(key) ]
            return [self.get(key) for key in self.keys() if self.get(key) ]
            
        def update(self, items):
            for key in items: self.__setitem__(key, items[key])

        def __contains__(self, item):
            return item in { key:value for key, value in iter(self) }

        def __iter__(self):
            return iter(self.items())
        
        def __repr__(self):
            return repr({ key:value for key, value in iter(self) })
        
        def __unicode__(self):
            return unicode(repr(self))
        

    class CacheChannelLayer(ChannelLayer):

        def __init__(self, *args, **kwargs):
            super(CacheChannelLayer, self).__init__(*args, **kwargs)
            self._channels = CacheDict(id="channels")
            self._groups = CacheDict(id="groups")
            
        def flush(self):
            self._channels.clear()
            self._groups.clear()
            
    channel_layer = ChannelLayer()

**Comment by andrewgodwin** [comment]
There's no way this will work - the cache will not synchronise across machines properly, and you'll get all sorts of errors about duplicate and missing messages. You just can't use a cache as a backend for channels at all.
