### ISSUE TITLE
`websocket.connect['headers']` should be a list of tuples

### ISSUE THREAD

**Issue by mjkillough** [andrewgodwin/channels#153]
`http.request['headers']` is a list of tuples. `websocket.connect['headers']` is a dict. They probably ought to be the same type, unless there's a good reason for them not to be.

@andrewgodwin says:

```
22:32:48 andrewgodwin | they were originally both dicts, but the websocket one got missed in the tuple conversion, it seems
22:32:52 andrewgodwin | could you file an issue?
22:33:08 andrewgodwin | I'll patch daphne and channels to use tuples
```

**Comment by andrewgodwin** [comment]
This is fixed in the latest Daphne release; no new Channels release is needed as it works with both types (which is what hid the bug).
