### ISSUE TITLE
Rename "runworker" to "worker"

### ISSUE THREAD

**Issue by oTree-org** [andrewgodwin/channels#158]
The idea is to rename `manage.py runworker` to `manage.py worker`. This is just a cosmetic suggestion that I am making because this command will be used so frequently. I acknowledge that `runworker` is consistent with `runserver`. However, consider that:

- "run" doesn't really add meaning to the command. IMO it is redundant. So, it would be good not to make "run" a naming convention for management commands. Consider the `manage.py shell` command (not `runshell`)
- `worker` is shorter to type
- Celery uses `celery worker`, Django-RQ uses `manage.py rqworker`, RQ uses `rq worker`, Pyres uses `pyres_worker`.

(Just a minor thing and a matter of taste.)

**Comment by andrewgodwin** [comment]
Hmm, you have a point, but internal consistency with `runserver` is also important; it's likely the command that Django users use most frequently, and so I'm not immediately convinced to rename away from it. Let me think about it.

(How I wish there was an aliasing system so they could both work, without having to make a subclass proxy)

**Comment by ssteinerx** [comment]
-1
runworker runs a worker as runserver runs a server

**Comment by andrewgodwin** [comment]
I'm going to say no on this one, we're too far along and it's kind of fixed now - plus `runserver` is a stronger existing pattern for me. I'm not saying it's a bad idea, just that we need to pick one option!
