### ISSUE TITLE
AsgiRequest' object has no attribute '_read_started' (called via tastypie)

### ISSUE THREAD

**Issue by pavanv** [andrewgodwin/channels#160]
{
  "error_message": "'AsgiRequest' object has no attribute '_read_started'",
  "traceback": "Traceback (most recent call last):
  File \"/home/pavanv/.virtualenvs/orgzit/local/lib/python2.7/site-packages/tastypie/resources.py\", line 219, in wrapper
    response = callback(request, *args, **kwargs)
  File \"/home/pavanv/.virtualenvs/orgzit/local/lib/python2.7/site-packages/tastypie/resources.py\", line 459, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File \"/home/pavanv/.virtualenvs/orgzit/local/lib/python2.7/site-packages/tastypie/resources.py\", line 481, in dispatch
    request = convert_post_to_put(request)
  File \"/home/pavanv/.virtualenvs/orgzit/local/lib/python2.7/site-packages/tastypie/resources.py\", line 2517, in convert_post_to_put
    return convert_post_to_VERB(request, verb='PUT')
  File \"/home/pavanv/.virtualenvs/orgzit/local/lib/python2.7/site-packages/tastypie/resources.py\", line 2509, in convert_post_to_VERB
    request._load_post_and_files()
  File \"/home/pavanv/.virtualenvs/orgzit/local/lib/python2.7/site-packages/django/http/request.py\", line 249, in _load_post_and_files
    if self._read_started and not hasattr(self, '_body'):
AttributeError: 'AsgiRequest' object has no attribute '_read_started'
"
}

This is different from issue #123, since I already have the fix for that in the channels package version I'm running.

Relevant package versions:
Django==1.8.13
channels==0.13.1
django-tastypie==0.13.3

**Comment by andrewgodwin** [comment]
Hmm, technically this is Tastypie accessing internals of the Request object it shouldn't; I'll see if I can work out a way to present `_load_post_and_files` properly though so this works.

**Comment by MiguelSR** [comment]
I have the same problem.

**Comment by pavanv** [comment]
@andrewgodwin have you looked further into this issue or will have the bandwidth to do so? This is blocking my application's deployment of web sockets, so it's a high priority issue for us. If it's not possible for you to look into this, I'll try to spend some time on it.

**Comment by andrewgodwin** [comment]
I'm afraid not; I have been focusing on higher priority stuff. You are free to take a look, or keep running HTTP requests via a WSGI server and only send WebSockets to daphne for the meantime.

**Comment by MiguelSR** [comment]
@pavanv I sent a pull request to Tastypie fixing this issue and they accepted. So you can work with the current stable version, or set daphne to get only websocket connections as @andrewgodwin said.

https://github.com/django-tastypie/django-tastypie/pull/1474

**Comment by pavanv** [comment]
Thanks @MiguelSR. I got it working with your fix to Tastypie.
