### ISSUE TITLE
ASGI spec: email.receive should probably handle duplicate headers

### ISSUE THREAD

**Issue by frasern** [andrewgodwin/channels#161]
The ASGI spec currently defines the `email.receive` channel's `headers` value as:

> Dictionary of unicode string keys and unicode string values, containing all headers, including `subject`. Header names are all forced to lower case. Header values are decoded from RFC 1342 if needed.

This won't handle the case of duplicate headers in an email. The `Received` header, for example, will usually exist multiple times. [RFC 5322](http://tools.ietf.org/html/rfc5322#page-21) has a table showing standard headers which can be repeated.

I note that for the HTTP and WebSocket channels, headers are defined as lists of `[name, value]` pairs, so perhaps the email channel should be the same. If so, it means the note about accessing `headers['from']` and `headers['to']` will also need to be amended.

It would be nice to use Django's [MultiValueDict](https://github.com/django/django/blob/1.9.6/django/utils/datastructures.py#L48), or similar, but I suspect that's not compatible with the serialization needs of Channels.

**Comment by andrewgodwin** [comment]
I had forgotten I even put that in there - it's not finished yet! I was still reading RFCs on the plane and writing it and committed that section by accident. I'll extract it out into a separate spec document so it's not in the main spec, and mark it as not-even-draft.

Also, you're right, and I'll fix headers to match! If you fancy helping fix out the rest of the spec, that would be great, as email has even more hidden edges than HTTP.

**Comment by frasern** [comment]
Certainly happy to look into this...

Are you definitely wanting to split out the headers and other parts of the email into Python dicts?

If we just had a single `data` entry that contained the RFC-compliant version of the email, then consumers could make use of the existing Python `email` library to parse and extract its data:

```python
import email

def email_consumer(message):
    msg = email.message_from_string(message['data'])
```

This more closely resembles SMTP, in that the message has a single `from` address, one or more `to` addresses and a single `data` block. I tend to this this makes more sense.

With the 1MB message limit, we'd need to have a `more_data` key that behaves like the HTTP channel's `more_body`.

**Comment by andrewgodwin** [comment]
My main concern is extracting enough out into the ASGI message that it can be routed appropriately without having to decode it first, which means I believe that at least one of the To: addresses (probably envelope To rather than message To) and the subject should be available outside easily.

And yes, this will need to work like `http.request` for fetching additional body, though I'm still not 100% sold on if that should be a random non-process-specific channel, or a boolean flag that tells the receiving client to make a process-specific channel, and send it back to the interface server to get the rest of the body.

**Comment by frasern** [comment]
Yes, you're right that certain info will be needed for routing -- I hadn't appreciated that.

It maybe makes sense to review what various email platforms actually include with incoming messages:

 * https://sendgrid.com/docs/API_Reference/Webhooks/parse.html#-Setup
 * http://developer.postmarkapp.com/developer-inbound-webhook.html#data
 * https://mandrill.zendesk.com/hc/en-us/articles/205583197-Inbound-Email-Processing-Overview#inbound-events-format
 * https://cloud.google.com/appengine/docs/python/mail/receiving-mail-with-mail-api#handling_incoming_email
 * http://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-notifications-contents.html

I imagine a common use-case would be for the POST data from one of these webhooks to be received via HTTP and then relayed over the `email.received` channel for further processing.

I'll try to work up a common set of data/headers.

**Comment by andrewgodwin** [comment]
Right, the whole point of an abstraction is that a webhook receiver, an IMAP poller, and a direct SMTP interface server should all be able to present the same information about an email, so you can build against the spec and swap out email implementation as required. I like the idea of looking at what everyone else is doing, there's a lot of value in learning from other work.
