### ISSUE TITLE
How to set password for connection with redis?

### ISSUE THREAD

**Issue by onegreyonewhite** [andrewgodwin/channels#164]
Is there any such option in the channel?
As this password is specified in the config file?

Now I use this config:
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "widget.routing.channel_routing",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
```

**Comment by andrewgodwin** [comment]
No, the backend does not support Redis passwords; I'll add it to the list of features to get in there, though encryption support is probably higher-priority as Redis passwords are really not secure.

**Comment by onegreyonewhite** [comment]
It seems to me you do not know all the possibilities of your product.
I used here is just these settings:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "widget.routing.channel_routing",
        "CONFIG": {
            "hosts": [("redis://:mypassword@127.0.0.1:6379/0")],
        },
    },
}
```
and it worked.

**Comment by andrewgodwin** [comment]
Ah, fair enough, I didn't realise the redis backend string did that.

**Comment by russelltao** [comment]
Does this issue fixed now???

**Comment by andrewgodwin** [comment]
Just follow the example above and set it in the connection string.

**Comment by Nuurek** [comment]
This commit resolves the issue: [Add redis's password from config to txredisapi. (#41)](https://github.com/django/asgi_redis/commit/96f9582536343c05d6f25cdd2316d4e4724aa309)

**Comment by aparnabushan** [comment]
Thank you so much @onegreyonewhite !

**Comment by devs001** [comment]
Hey thanks for  it save me alot alot of headache.
Thanks.🙏🙏🙏

**Comment by malmukhtar** [comment]
Thank you very much, I've been trying to solve this issue for a couple of days with no luck.

**Comment by vishwas-chill** [comment]
Thanks a lot, it worked @onegreyonewhite. But can anyone help me with the reason, why it works?

**Comment by onegreyonewhite** [comment]
> Thanks a lot, it worked @onegreyonewhite. But can anyone help me with the reason, why it works?

This works because ConnectionPool supports url scheme.

**Comment by TonyYanOnFire** [comment]
Notice that python ignores parentheses when wrapping single element, so 
```
"hosts": [("redis://:mypassword@127.0.0.1:6379/0")],
```
euqals
```
"hosts": ["redis://:mypassword@127.0.0.1:6379/0"],
```
however,  leving a comma at the end makes it a tuple, and acceable tuple format should be (host, port), so code below will cause error
```
"hosts": [("redis://:mypassword@127.0.0.1:6379/0", )],
```
