### ISSUE TITLE
Persist channel_session after connection is closed

### ISSUE THREAD

**Issue by alfetopito** [andrewgodwin/channels#165]
As far as I've looked, it isn't possible to persist a `channel_session` outside of it's life cycle, as the doc states https://github.com/andrewgodwin/channels/blob/363b5a09e917b7b3a97981516202e9b7ce248366/channels/sessions.py#L39.

Besides, only `http_channel` looks for the session cookie or session_key GET parameter https://github.com/andrewgodwin/channels/blob/363b5a09e917b7b3a97981516202e9b7ce248366/channels/sessions.py#L169

In my usecase, I will have only ws connections, so there won't be an active http session to rely on.
I would like that upon `websocket.connect`, the same `channel_session` to be used, if either session cookie or session_key is set.

Is there a way to do that already or would I need to implement a custom solution?

**Comment by andrewgodwin** [comment]
WebSockets lack the ability to set cookies, so there's no way of persisting the session after the channel is closed. Instead, the only thing to do would be to somehow give the user a HTTP session via a traditional HTTP request, and then use `http_session` inside and access that overarching session from the websockets.
