### ISSUE TITLE
Possible to find Channel name based on session or user that is outside of consumers?

### ISSUE THREAD

**Issue by theTarkus** [andrewgodwin/channels#169]
(Sorry, in advance!)

I've read through the docs but I was not able to find any information about if it is possible to find Channel name based on session or user that is outside of consumers.

Let's say I've got a signal after a model instance is created and I want it to then send a message to that user that the instance was created, but I also want to send it to a session (stored in model instance; someone else's session, not the user).

But these messages should be private since they need to be sent individually.

Using django-websocket-redis I can achieve it doing something like this for user:
`RedisPublisher(facility="user", users=[instance.user.username])`
or for session:
`RedisPublisher(facility="anonymous", sessions=[instance.session])`

Is this possible with channels? Or is the best way to add the user and the session client to separate groups and then send message through groups?

I read this beforehand:
https://github.com/andrewgodwin/channels/issues/106

**Comment by andrewgodwin** [comment]
You should use Groups for this, just keyed off of user ID or session key, in a very similar way to the RedisPublisher example. Groups are in general the way to send messages to something other than a specific open websocket connection identified by reply_channel.
