### ISSUE TITLE
runserver_plus (Werkzeug)

### ISSUE THREAD

**Issue by xeor** [andrewgodwin/channels#170]
Would getting support for another runserver (runserver_plus from the django-extensions project), be in the scope of the channels project, or the django-extensions project?

I got super-exited about channels, but I don't want to loose runserver_plus and the werkzeug debugger.

I found no mentioned in this github repo for runserver_plus/werkzeug and no mention of channels in https://github.com/django-extensions/django-extensions..

Thoughts?

**Comment by andrewgodwin** [comment]
Another runserver would be valuable, but given that the existing Channels `runserver` is an entirely new WebSocket-compatible server written to support it, you wouldn't just be able to port werkzeug - it doesn't support WebSockets from what I understand, so it won't work in this context.

**Comment by andrewgodwin** [comment]
I'm closing this for now, since it's outside the scope of the main channels project. It would still be nice to have, but it requires a lot of effort on the werkzeug end.
