### ISSUE TITLE
Error 'Got invalid WebSocket reply message'

### ISSUE THREAD

**Issue by muhammadfarizarya** [andrewgodwin/channels#177]
I have update channels to 0.14.0, but when I try send to socket getting error like in below.
`unknown_message_keys,
exceptions.ValueError: Got invalid WebSocket reply message on websocket.send!LVyxDMxF - contains unknown keys set(['results'])`
I have trying to downgrade channels to 0.13.1 but getting same error, are channels can not work alongside with django rest framework? Thank you

**Comment by andrewgodwin** [comment]
This means you're sending an invalid message down the reply channel of the websocket - previous versions of Channels just dropped the invalid content, but now it complains.

You likely are doing `send({"results": ... })` when you mean to do `send({"text": json.dumps({"results": ... })})`.

**Comment by muhammadfarizarya** [comment]
I have try with `json.dumps()` but getting same error, this is my code on consumers.py on websocket.recieve : 
`result_one = ModelNameOne.objects.filter(field__isnull=False)
 result_two = ModelNameTwo.objects.filter(field__isnull=False)
 result = list(chain(result_one, result_two))
 data = serializers.serialize("json", result)

 message.reply_channel.send({
       'results': json.dumps({ "data": data })
  })`
are it cant send serialized django models?

**Comment by andrewgodwin** [comment]
You're sending the wrong message over the channel. A message to a WebSocket channel can have only these three keys:

* text: Sends a WebSocket text frame with the content
* bytes: Sends a WebSocket binary frame with this content
* close: Closes the WebSocket from the server side

Passing in "results" makes no sense; it's not one of the three WebSocket server keys that's allowable.

Now, what you probably want is to send a dict that has the key "results" as the message - to do this, you must encode the whole dictionary with that key as JSON and send it as a text frame, as my example before was showing.

**Comment by muhammadfarizarya** [comment]
So, it must be send those three keys, thank you @andrewgodwin it works

**Comment by tmiller02** [comment]
@andrewgodwin I was wondering if the documentation needs to be updated to reflect this, or if I am misunderstanding the issue. Some of the code snippets under [Channel Concepts](http://channels.readthedocs.io/en/latest/concepts.html#groups ) give an example of sending a message like:

```
Group("liveblog").send({
    "id": instance.id,
    "content": instance.content,
})
```

Should this instead be something like:

```  
Group("liveblog").send({
        "text": json.dumps({"id": instance.id, "content": instance.content})
})
```

**Comment by andrewgodwin** [comment]
Yes, that should be the latter type! Do you want to submit a PR?

**Comment by tmiller02** [comment]
Sure, I'll open a PR shortly

**Comment by rschwiebert** [comment]
I ran into this during the tutorials because of things like this in the consumers.py: `message.reply_channel.send({"accept": True})`

which produced

`Got invalid WebSocket reply message on websocket.send!bkZgiRIqCWok - contains unknown keys {'accept'}`

So... the tutorial needs to be tweaked? Actually I did not even glean what the `'accept': True` does for the channel.  Be kind, I just started with Channels this morning :)

**Comment by andrewgodwin** [comment]
Ah my apologies, the version up there is for the in-development `master` branch, which has some major changes compared to the current one. Let me get the docs version pinned to stable.

**Comment by andrewgodwin** [comment]
Alright, I switched the docs so `stable` is the default version - you can see the correct version for the one you can download at http://channels.readthedocs.io/en/stable/getting-started.html

**Comment by divonelnc** [comment]
The tutorial on http://channels.readthedocs.io/en/stable/getting-started.html still has an example using 

`# Stick the message onto the processing queue
    Channel("chat-messages").send({
        "room": message.channel_session['room'],
        "message": message['text'],
    })`

Is the tutorial not up to date or am I doing something wrong? As I have the `Got invalid WebSocket reply message` error
