### ISSUE TITLE
Provide documentation for websocket clients

### ISSUE THREAD

**Issue by traverseda** [andrewgodwin/channels#179]
Using django as a websocket client is a good way to implement things like federated services, RPCs, etc. In particular I'm interested in integrating django with the kurento media server.

Support for django websocket clients would be very helpful, as would documentation on how to use it.

**Comment by andrewgodwin** [comment]
Channels doesn't provide WebSocket client support, as it would require a whole new interface server to use it (WebSocket clients must be run from an asynchronous environment, and so cannot be run from the Django side) - this is out of scope of the Channels project as it stands, but I'm hoping a third party app could eventually fill in the gap here.
