### ISSUE TITLE
Common error hook point for Sentry/Raven

### ISSUE THREAD

**Issue by oTree-org** [andrewgodwin/channels#180]
Sentry is not receiving exceptions raised inside my channels consumers. I have a simple default `RAVEN_CONFIG`:

```
RAVEN_CONFIG = {'dsn': 'my_dsn...'}
```

I know I could manually use `client.captureException` inside every consumer as described [here](https://docs.getsentry.com/hosted/clients/python/#capture-an-error), but looking for a cleaner way.

**Comment by andrewgodwin** [comment]
Sentry would need some way of wrapping around the entire consumer system, in a way akin to middleware for views, which Channels doesn't have quite yet (though there is a clear place I left to add it in)

**Comment by andrewgodwin** [comment]
Do we know if having a custom named logger that errors go into would be good enough for Sentry/Raven integration?

**Comment by andrewgodwin** [comment]
Closing as I think logger integration is cleaner.
