### ISSUE TITLE
Routing problems

### ISSUE THREAD

**Issue by Wirzi** [andrewgodwin/channels#181]
Hello

I have some problems using the path argument for includes.

I have a routing setup like:

```
omniboard_routing = [
    include(frontend_routing, path=r"^/frontend"),
    include(backend_routing, path=r"^/backend"),
]
```

And the routing for each include looks like this:

```
frontend_routing = [
    route("websocket.connect", board.connect),
    route("websocket.receive", board.message),
    route("websocket.disconnect", board.disconnect),
]

backend_routing = [
    route("websocket.connect", consumer.connect),
    route("websocket.receive", consumer.message),
]
```

Open to websocket connection works as expected, but no messages arrives from the server.
In the worker log i see this message.

> ERROR - worker - Could not find match for message on websocket.receive! Check your routing.
 
If i rearrange the routing like this:

```
omniboard_routing = [
    include(frontend_routing, path=r"/frontend"),
    include(backend_routing, path=r"/backend"),
]
```

only the `/backend` part works and the server sends back messages.
Is this a bug?
With the runserver both entries working as expected.

**Comment by andrewgodwin** [comment]
Hm, I tried to reproduce this and couldn't. Could you tell me what versions of `channels`, `daphne`, `asgiref`, `asgi_redis` (if installed) and Django you're using, along with your `CHANNEL_LAYERS` setting?

**Comment by Wirzi** [comment]
Installed versions are:

`daphne==0.12.1`
`channels==0.14.0`
`asgiref==0.13.0`
`asgi-redis==0.12.0`

Settings are:

```
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "asgi_redis.RedisChannelLayer",
            "ROUTING": "project.routing.base.project_routing",
        },
    }
```

**Comment by andrewgodwin** [comment]
Could you give me the `project_routing` as well, since this is a routing issue? Or at least, some minimal version of it that helps reproduce the issue?

As for your second problem, I suspect it may be that the worker process is freezing up/erroring at some point, which is why further requests get ignored. Is it possible there's error logs from the worker you're not seeing?

**Comment by Wirzi** [comment]
I have figured it out.
The nginx configuration pipes all the request for web-sockets to the path `/websocket/` and i didn't used this path in the include tag for the routing. =S
Thanks for the help.
