### ISSUE TITLE
Invalid Call to InMemoryChannelBackend

### ISSUE THREAD

**Issue by ricomoss** [andrewgodwin/channels#20]
After installing channels and creating a shell Django website I am unable to get a basic runserver started due to the following error:

```
Unhandled exception in thread started by <pydev_monkey._NewThreadStartupWithTrace instance at 0x7f69673e13f8>
Traceback (most recent call last):
  File "/usr/lib/pycharm-4.5.3/helpers/pydev/pydev_monkey.py", line 427, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "/home/ricomoss/.virtualenvs/dc2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/ricomoss/workspace/channels/channels/management/commands/runserver.py", line 25, in inner_run
    self.channel_backend = channel_backends[DEFAULT_CHANNEL_BACKEND]
  File "/home/ricomoss/workspace/channels/channels/backends/__init__.py", line 32, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/home/ricomoss/workspace/channels/channels/backends/__init__.py", line 26, in make_backend
    instance = backend_class(**{k.lower(): v for k, v in self.configs[name].items() if k != "BACKEND"})
TypeError: __init__() takes at least 2 arguments (1 given)
```

After investigating I was able to see that the default channel backend is going to be `channels.backends.memory.InMemoryChannelBackend`, which expects a `route` to instantiate.  The dictionary comprehension above is empty.

I'd love to contribute to this project but have just started and do not have the full context of intent here.  Can you please provide some guidance as to what can be done to fix this problem?

**Comment by ricomoss** [comment]
If I update `BaseChannelBackend`'s `__init__` definition to:

```
def __init__(self, routing=None, expiry=60):
```

I am able to launch the dev runserver.  I will continue with this change unless you specify otherwise.

**Comment by ricomoss** [comment]
I see now that I did not follow the docs far enough.  I assumed that I would be able to run Django without an initial setup of channels.  Oops.

I think it might be worth noting in the docs that Django will not run with channels installed unless channels is configured properly.

**Comment by andrewgodwin** [comment]
No, you're right, Django should run without any config if you just install "channels" - it's likely I just missed something when adding routes as an argument to backends.
