### ISSUE TITLE
make_backend causing failure in tests

### ISSUE THREAD

**Issue by meshy** [andrewgodwin/channels#200]
Hello! Thanks for this fantastic project. I hope you don't mind my asking for help!

I've been trying to get multiple apps running from the same codebase on the same server (ref https://github.com/andrewgodwin/daphne/issues/16).

I have upgraded a few local packages...:
```diff
-asgi-redis==0.10.0
+asgi-redis==0.12.0
-asgiref==0.11.2
+asgiref==0.13.0
-channels==0.12.0
+channels==0.14.0
```

...and configured my `CHANNEL_LAYERS` setting:

```python
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "core.routing.channel_routing",
        "CONFIG": {"hosts": ["redis://localhost:6379/0"]},
    },
    "api": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "core.routing.channel_routing",
        "CONFIG": {"hosts": ["redis://localhost:6379/1"]},
    },
}
```

... but have been getting errors in my tests:

```pytb
...
  File ".../users/models.py", line 96, in save
    Channel('update-user').send({'user_id': self.pk})
  File ".../site-packages/channels/channel.py", line 30, in __init__
    self.channel_layer = channel_layers[alias]
  File ".../site-packages/channels/asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File ".../site-packages/channels/asgi.py", line 44, in make_backend
    asgi_layer = backend_class(**self.configs[name].get("CONFIG", {}))
TypeError: __init__() got an unexpected keyword argument 'hosts'
```

~~This happens regardless of whether I use `channels.tests.ChannelTestCase`.~~ **EDIT** Ok, sorry, I was wrong about that `:P` It turns out my test runner was overriding the default backend.

I'm unsure If I have done something wrong, or if I have stumbled upon a bug.

Any chance you could help me shed some light on the issue? Is there any more information that I could provide to clarify things?

**Comment by meshy** [comment]
Ok, after a little more investigation, I have found that adding (and ignoring) `**kwargs` to [`asgiref.inmemory.ChannelLayer.__init__()`
](https://github.com/andrewgodwin/asgiref/blob/d87eb4102200c325959e5981e8813f7d8992e981/asgiref/inmemory.py#L19) seems to alleviate the symptoms of the issue.

Does this seem like a "correct" fix to you?

**Comment by andrewgodwin** [comment]
No, the correct fix is to modify the test code to not preserve configuration arguments when the inmemory backend is swapped in to run tests :)

I can look at this at some point, or you're free to patch it if you like.

**Comment by andrewgodwin** [comment]
OK, looked into this further, and the actual real fix is probably adding the other alias you want to test to `test_channel_aliases` on your ChannelsTestCase subclass, as it only swaps out `default` by default.
