### ISSUE TITLE
Access HTTP session from consumer

### ISSUE THREAD

**Issue by chesstrian** [andrewgodwin/channels#204]
Hi,

I was wondering if it's possible to access user data in HTTP session from consumer?, in order to get user info if such user is logged in.

Thanks in advance.

**Comment by andrewgodwin** [comment]
Yes, please see the portion of the documentation that covers this: http://channels.readthedocs.io/en/latest/getting-started.html#authentication

**Comment by chesstrian** [comment]
Amazing! :smile: thanks a lot.
