### ISSUE TITLE
--noasgi on one django instance breaks another instance of same project

### ISSUE THREAD

**Issue by michael-k** [andrewgodwin/channels#205]
I've created a [small example project](https://github.com/aexeagmbh/channelsexample)¹ that resembles our environment using docker compose.  There's postgres, redis and Django.  The Django project is distributed over a few docker containers.  The example project uses one container to handle HTTP requests (in this case, only the admin is of interest) and another container to handle websockets.

When starting the project (see project's readme), connecting to the websocket via a brower console and sending something over the regarding channel, everything works fine.

The thing we do not understand is, that as soon as we start the web container with `--noasgi` (in [this line](https://github.com/aexeagmbh/channelsexample/blob/master/docker-compose.yml#L8)), it does not work any more.  Meaning the browser is not receiving any data sent over the websocket.  It prints “websocket connected“, but nothing else.

Note that we use the shell plus within the websocket container to call `Group(…).send(…)`.  The web container should not be involved in any way.  At least we do not see why.

Without `--noasgi`, the websocket container prints `DEBUG    Sent WebSocket packet to client for websocket.send!ZnhjrkaqrjAd`, with it, it prints nothing.

We could reproduce this on two different computers.

Our main goal is to restrict the web container that it only ever handles HTTP (and in the future HTTP2) requests, but does not care about web sockets.  So we thought `--noasgi` could be the right parameter for this case.

¹ https://github.com/aexeagmbh/channelsexample

**Comment by michael-k** [comment]
And as a minor goal, I'd like to improve my understanding of channels. :)

**Comment by thewayiam** [comment]
Through [doc](https://channels.readthedocs.io/en/latest/deploying.html#run-interface-servers), in my undertanding, --noasgi let your django use the previous WSGI server, and it won't know channels worker(which deal with websocket) run on which port, you might need some interface server to manage that, something like nginx might what you need.

**Comment by andrewgodwin** [comment]
How are you routing requests between either the http-only server or the websocket server? Typically problems like this are misconfigurations at the load balancer/proxy level.

**Comment by michael-k** [comment]
In this case they are bound to different ports of the localhost.  The container running the http-only server exposes port 8042 and the container running the websocket server exposes port 9999. See https://github.com/aexeagmbh/channelsexample/blob/master/docker-compose.yml

In our production environment there's a nginx in front of them and routes based on the url (all websocket endpoints are under `/ws`).

Nevertheless, when opening a shell plus in the container running the websocket server, it never sends any payload over the wire.  The message `DEBUG Sent WebSocket packet to client for websocket.send!ZnhjrkaqrjAd` only appears if the http-server has been started without `--noasgi`.  Using the javascript code
```javascript
var wsAddress = "ws://localhost:9999/ws/project/1/",
    socket = new WebSocket(wsAddress);
socket.onmessage = function(e) {
    console.log({onmessage: JSON.parse(e.data)});
};
socket.onopen = function() {
    console.log("websocket connected");
};
socket.onclose = function() {
    console.log("websocket disconnected");
};
```
(see https://github.com/aexeagmbh/channelsexample/blob/master/README.md#dev-setup), I connect directly to the container running the websocket server.

**Comment by andrewgodwin** [comment]
Oh, right, it's because you're not running a worker server. Whenever you run daphne, you must also run at least one worker server (`runworker`). `runserver` in ASGI mode includes some, which is why it works when you enable that.

Please don't use the normal WSGI Django `runserver` in production, too; it's not designed for that, you should opt to use gunicorn or similar WSGI servers instead, which would match well with using Daphne for ASGI.

Docs on this are here: http://channels.readthedocs.io/en/latest/deploying.html#run-worker-servers
