### ISSUE TITLE
Is Channel thread safe ?

### ISSUE THREAD

**Issue by chenlucan** [andrewgodwin/channels#215]
Not sure if I use Channels correctly.

I'm using Channels handling websocket messages:

- Convert and Send user websocket msg to backend RabbitMQ

- Receive & push backend RabbitMQ msg to user through websocket

Since Channel workers and RabbitMQ are separate threads, 

- Is Group thread safe(add/discard/send) ?

- How to share global objects across multiple workers/threads?

**Comment by andrewgodwin** [comment]
Yes, Channels is thread-safe in every sense of the word; its very design actually means it's also process-safe and machine-safe, in that the primitives work from anywhere in the network atomically.

I don't know what you mean about sharing global objects; Channels is meant to run as multiple processes, so the only place you can share state is either via message-passing (channels itself) or a backing datastore (e.g. a database)
