### ISSUE TITLE
Cancel jobs?

### ISSUE THREAD

**Issue by romanlv** [andrewgodwin/channels#216]
Is there a way to cancel long running jobs? Especially those that are 'block'ed by waiting for output from other subprocesses (e.g. shell command with `subprocess.Popen`)

Also, it's not clear how to get the list of currently executing tasks, redis only contains keys for groups and response channels. 

Basically, I'm trying to create `lightweight Jenkins` in python...

**Comment by andrewgodwin** [comment]
No - channel consumers aren't jobs, and they're not supposed to be super-long-running, so there's no concept of "job state" or similar. You'd want to layer a job system on top of Channels, using channels for starting jobs and receiving job state, but adding things like state tracking, job identifiers, and job actions (like cancel).

You might want to look at Celery which provides a bit more of this functionality as it has tasks that are revokeable.
