### ISSUE TITLE
websocket.receive processed before websocket.connect

### ISSUE THREAD

**Issue by claytondaley** [andrewgodwin/channels#220]
Is it possible that `websocket.receive` is processed before `websocket.connect` for the same connection?

I was migrating an application using [channels-examples](https://github.com/andrewgodwin/channels-examples) as a reference and was having issues with [this line](https://github.com/andrewgodwin/channels-examples/blob/08963c45afbeaed983a7f046fdb89c5374b0b846/multichat/chat/consumers.py#L72).  In our case, the "join" operation is run as part of the browser's `onopen` command.  After adding a bunch of logging, it looks like `websocket.receive` is running before `websocket.connect` so the array isn't initialized in time.

I've seen no positive statement that the order is guaranteed, but the same assumption seems to be baked into the example... that `websocket.connect` completes before the response that triggers `onopen` on the client.  Can someone confirm that this is *not* the expected behavior?

**Comment by andrewgodwin** [comment]
Please see the section of the docs about guaranteeing in-order operation of endpoints: http://channels.readthedocs.io/en/latest/getting-started.html#enforcing-ordering
