### ISSUE TITLE
How to get keyword arguments in class based consumers

### ISSUE THREAD

**Issue by AlexejStukov** [andrewgodwin/channels#224]
The [docs](http://channels.readthedocs.io/en/latest/routing.html#filters) imply that you can get keyword arguments from the filters e.g. `slug` from `route("websocket.connect", connect_blog, path=r'^/liveblog/(?P<slug>[^/]+)/stream/$')`. How and where do I get them in a class based consumer?

**Comment by AlexejStukov** [comment]
Nvm, found that you can get them in the `kwargs` in `connect` and `connection_groups`.

**Comment by AlexejStukov** [comment]
Clarification in #225. It also might be a good idea to add them to the ctor-kwargs, if possible?

**Comment by andrewgodwin** [comment]
The ctor-kwargs?

**Comment by AlexejStukov** [comment]
Oh, I'm sorry. I mean the ``__init__``-method.

**Comment by andrewgodwin** [comment]
I've added a change that provides them as `self.kwargs` - will be out in the next release.

**Comment by AlexejStukov** [comment]
Thanks, that's really great. Especially that you can now use ``SingleObjectMixin`` and others out of the box...
