### ISSUE TITLE
Multiple Connections using channels.

### ISSUE THREAD

**Issue by new-player** [andrewgodwin/channels#226]
I want to achieve a functionality of real time notifications and chats. Till now I have already implemented chat feature using channels. Now on the same page I also want to add realtime notification feature on the same page.
Do I need to initialize a new websocket connection or the same connection can be used to manage both functionalities?

**Comment by andrewgodwin** [comment]
You can multiplex both down the same connection, you'll just need to add markers to the messages sent to say what they're for and write code that handles that on the client side.

**Comment by adamshamsudeen** [comment]
@new-player I was wondering if you were able to solve it? I am using channels to send notifications and tracker user activity, but sometimes the changes are not saved to the db. What could be the issue? Please help.

**Comment by Tjorriemorrie** [comment]
@andrewgodwin so no link to docs about this?

**Comment by andrewgodwin** [comment]
I'm in the progress of writing up the Channel 2 docs that will include a section about this.

**Comment by maryokhin** [comment]
@andrewgodwin is there a way to route to different consumers? So that I can keep the consumer code separate. Or it has to be one consumer?

**Comment by andrewgodwin** [comment]
@maryokhin I'm not quite sure what you mean - are you talking about channels 1 or 2?

**Comment by maryokhin** [comment]
@andrewgodwin Channels 2. Basically I want to have 2 apps, I.e. /chat and /notification share the same websocket connection to the browser. What's the best way to do this with channels? I was thinking about somehow routing to 2 different consumers via the routing config.

Basically, what's the best way to multiplex in Channels 2?

**Comment by andrewgodwin** [comment]
@maryokhin Until multiplexing support lands in Channels 2, you will have to do it yourself, which means writing a single consumer that listens to the socket and demultiplexes appropriately. If you want, you can make that consumer dispatch out to two other consumers, but you always need a single _thing_ on the end of a socket (channels' demultiplexing support is just that written so you can pass in other consumers and it handles them properly)

**Comment by sahdev0** [comment]
**@andrewgodwin** 

Hello,

I am implementing a websocket application for live data feed updates to each client according to their watchlist. I am explaining my requirement:

1) Once user register with my application, he can view list of currency pairs e.g (ETH, BTC etc)
2) From that list, user can add one or more pairs into his watchlist.
3) And based on user's watchlist, user should get only that data through "Channel"

Possible approach as per me:

1) Should i create multiple channel for each user ? or 
2) Is there possibility to create multiple events in single channel to handle each user separately to send different feeds to each user

Please kindly suggest, what is the right approach to implement this kind of situation.

**Comment by maryokhin** [comment]
@andrewgodwin thanks for the tips. Last question: is it confirmed that Channels 2 will have multiplexing and if yes do you know approximately when it'll happen? Thanks again.

**Comment by andrewgodwin** [comment]
@sahdev0 Please ask long questions like this on the django-users mailing list - if you mention "channels" I'll see it and answer it there.

@maryokhin I hope to get it in but I can't give hard dates on things like this. There's a branch with it mostly finished called "multiplexing" but it's quite out of date now.

**Comment by sahdev0** [comment]
**@andrewgodwin**  Ok i am posting this question again on django-users mailing list. In short if you undrestand my problem can this be possible

**Comment by MonkeyPengc** [comment]
> You can multiplex both down the same connection, you'll just need to add markers to the messages sent to say what they're for and write code that handles that on the client side.

Hello, just fixed the same issue, thanks for the heads up.
