### ISSUE TITLE
Test Failure when declaring setUp

### ISSUE THREAD

**Issue by lcannon** [andrewgodwin/channels#229]
Thanks for the great project!

I've been writing tests for the socket messages we pass, and got the error:

```
======================================================================
ERROR: test_status_changed (accounts.tests.TestConnectionEvents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/venv3/lib/python3.4/site-packages/channels/tests/base.py", line 52, in tearDown
    channel_layers.set(alias, self._old_layers[alias])
AttributeError: 'TestConnectionEvents' object has no attribute '_old_layers'

----------------------------------------------------------------------
```

The error was very easy to find and fix -- not calling `super` in `setUp`, but maybe it'd be good to add a note about ensuring you call setUp's super if you override it in the docs?

**Comment by lcannon** [comment]
Happy to make a pull request for this if that'll help.

**Comment by andrewgodwin** [comment]
Sure, I'll take a PR - it's generally good form to call super.setUp in any test suite, but worth reminding people :)

**Comment by vikalpj** [comment]
@andrewgodwin What do you think about overriding django level _pre_setup() and _post_teardown()... this way there would be no need to call super().setUp() as all the things would be handled at api level itself.

**Comment by andrewgodwin** [comment]
Agreed - merged your PR.
