### ISSUE TITLE
Docker, ASGI, Nginx & Channels

### ISSUE THREAD

**Issue by nux17** [andrewgodwin/channels#234]
Hello,

I'm working on a production set up.

I've Docker containers for Nginx, Redis, Postgres, and I don't know if I might run daphne and django workers on two separated containers (scaling purpose). I would like to do that, but how could I?

Aswell, how can I split Nginx conf to serve regular HTTP requests and Websockets both to daphne, should I just skip the connection Upgrade?

Thanks

**Comment by andrewgodwin** [comment]
- If you want to have Daphne do both, you still need to make sure nginx passes the Connection header through, but not force it to upgrade, like this:

```
http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        ...
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
```

- You can run Daphne and the workers in separate containers or the same one, as long as they're both pointing to the same Redis backend. They'll communicate via Redis. I might suggest that you bundle one daphne and a few workers into a single container with the RedisLocal backend for better performance, but that's not required.
