### ISSUE TITLE
Twisted version 16.3.0 breaks websocket.receive

### ISSUE THREAD

**Issue by whusterj** [andrewgodwin/channels#237]
[Please have a look at this question on StackOverflow](http://stackoverflow.com/questions/38237120/django-channels-echo-example-not-working).

I had the same problem with the echo example. I downgraded Twisted to 16.2.0 and it began working as expected.

**Comment by andrewgodwin** [comment]
Interesting. Will try to work out why this weekend.

**Comment by andrewgodwin** [comment]
Have pinned `daphne` (the package that uses Twisted) to 16.2 or below for now to stop it pulling in a broken version. I'm moving this bug over to the Daphne issue tracker as andrewgodwin/daphne#31
