### ISSUE TITLE
The "Getting Started" tutorial does not seem to work

### ISSUE THREAD

**Issue by senden9** [andrewgodwin/channels#238]
Hi,
I follow the [introduction](http://channels.readthedocs.io/en/stable/getting-started.html) but it seems that the `websocket.receive` method isn't called. The question is now if it is my fault, a error in the introduction or a bug in channels.
Here are the relevant package versions that i use:
```
asgi-redis==0.13.1
asgiref==0.13.3
autobahn==0.14.1
channels==0.16.0
daphne==0.14.2
Django==1.9.7
redis==2.10.5
Twisted==16.3.0
```

consumer.py
``` python
from channels import Group

# Connected to websocket.connect
def ws_add(message):
    Group("chat").add(message.reply_channel)
    Group("chat").send({
        "text": "New user here!",
    })

# Connected to websocket.disconnect
def ws_disconnect(message):
    Group("chat").discard(message.reply_channel)

# Connected to websocket.receive
def ws_message(message):
    Group("chat").send({
        "text": "[user] %s" % message.content['text'],
    })
```

routing.py
``` python
from channels.routing import route
from tailIt.consumers import ws_add, ws_message, ws_disconnect

channel_routing = [
    route("websocket.connect", ws_add),
    route("websocket.receive", ws_message),
    route("websocket.disconnect", ws_disconnect),
]
```

A snippet of settings.py:
``` python
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "tail_log.routing.channel_routing",
    },
}
```

I used Wireshark to verify the data transmission between the server and Firefox. At the connect to the websocket i get the message "New user here!". But if i send something via `socket.send("something")` i see the message goes to the server but nothing returns to the browser.
As far as i understand django/channels should return a message like "[user] something".

**Comment by andrewgodwin** [comment]
Unfortunately it looks like you've run into the bug with Twisted 16.3 outlined in #237 - just downgrade Twisted to 16.2. Daphne should have forced this by default when you installed it, so it's strange you got the wrong version - do you still have the installation logs anywhere?

**Comment by senden9** [comment]
Thanks i read this just at the moment in the [changelog of daphne
](https://github.com/andrewgodwin/daphne/commit/d17394e84c494e7faf0ddfc6375ff83b9fc6ccb3) 

I upgraded before a few hours via `pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U`. So pip upgraded twisted after channels. So i got incompatible versions. If i just use `pip install -U channels` twisted get downgraded automatically. It seems that pip doesn't check if it is safe to upgrade a package.

**Comment by andrewgodwin** [comment]
Urgh, that's annoying. A fix is on its way upstream into Autobahn, so hopefully this won't be a problem for too long.
