### ISSUE TITLE
How to pass message.reply_channel to background worker like Celery?

### ISSUE THREAD

**Issue by VincentTide** [andrewgodwin/channels#239]
Let's say I have a long running process in a Celery task that is started by Channels websockets. I want to use message.reply_channel to send a message back to the browser client that the long running process has completed.

Or put another way, I want to be able to save the reply address so that I can do something and later still send a message to the client that requested the work. Printing out message.reply_channel gives me this:

`websocket.send!hYQTrNNbMQpA`

I assume that is the unique identifier for the browser client that is suppose to receive the response but I'm having trouble figuring out how to send the message back to him.

**Comment by andrewgodwin** [comment]
Right - just pass that string along to a background task, and then use this to send messages to it:

```
from channels import Channel

def some_task(...):
    Channel(reply_channel_name).send(text=your_content_here)
```

You can treat `Channel(name_of_reply_channel)` exactly the same as `message.reply_channel`.

**Comment by VincentTide** [comment]
Thanks. That solved it. :)
