### ISSUE TITLE
Channels creates a new session object for each web socket

### ISSUE THREAD

**Issue by Sand1929** [andrewgodwin/channels#240]
Hello,

So it's my understanding that Channels seems to create a new session to track each web socket. For example, I'm using django-redis (4.4.3) to handle sessions, and if I have some consumers such as:

```
@channel_session_user_from_http
def ws_connect(message, model_id):
	try:
		obj = SomeModel.objects.get(id2=model_id)
	except SomeModel.DoesNotExist:
		return
	# add user to group corresponding to their object
	Group("namespace-%d" % obj.id2).add(message.reply_channel)

@channel_session_user
def ws_disconnect(message, model_id):
	try:
		obj = SomeModel.objects.get(id2=model_id)
	except SomeModel.DoesNotExist:
		return
	# remove user from group corresponding to their object
	Group("namespace-%d" % obj.id2).discard(message.reply_channel)
```

along with a standard setup for Redis: 

```
REDIS_HOST = get_env_variable('REDIS_HOST')
REDIS_PORT = get_env_variable('REDIS_PORT')

CACHES = {
	"default": {
    	"BACKEND": "django_redis.cache.RedisCache",
		"LOCATION": "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0",
    	"OPTIONS": {
        	"CLIENT_CLASS": "django_redis.client.DefaultClient",
    	}
	}
}

CHANNEL_LAYERS = {
	"default": {
		"BACKEND": "asgi_redis.RedisChannelLayer",
		"CONFIG": {
			"hosts": [(REDIS_HOST, int(REDIS_PORT))],
		},
		"ROUTING": "project.routing.channel_routing",
	}
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
```

then if I have a page that creates a new web socket with:

```
socket = new WebSocket("wss://" + window.location.href.split('://')[1]);
```

then if I navigate to that page and refresh twice, I'll get the following keys in redis:

```
1) ":1:django.contrib.sessions.cachedvcxw1pk3t54xxyjgjnmoi2liq00xt8n"
2) ":1:django.contrib.sessions.cachechna7c473f622cf82dd1ba4766d8167d"
3) ":1:django.contrib.sessions.cachechnc67df546f831ce06fedee86626dac"
4) ":1:django.contrib.sessions.cachechnb677411446c15a30cb183709233be"
```

The first is the session for the user, and my understanding is that the other three are for each of the new web sockets created each time I navigated to that page. If I want my sessions to have a lifetime of 2 weeks, it seems like I could end up with an awful lot of sessions stored in Redis. Am I doing something wrong? And if not, could there be a way to set different lifetimes for http vs web socket sessions?

Python version: 3.4.3
Django version: 1.9.7
channels version: 0.16.0
daphne version: 0.14.2
asgi-redis version: 0.13.1

**Comment by andrewgodwin** [comment]
If you opt for channel sessions then yes, there is one per socket - that's an unfortunate fact of life. You can, however, set a different session engine for channel sessions with `CHANNEL_SESSION_ENGINE`, which you could use to point to a subclass with a different expiry time set.

**Comment by Sand1929** [comment]
Got it. Thanks!
