### ISSUE TITLE
Closing websockets in generic consumers

### ISSUE THREAD

**Issue by approxit** [andrewgodwin/channels#244]
Hi, CBVs guy here.

Using generic websocket consumers I came across the need of closing connection with last message. Unfortunately right now I need manually make complete message - for JSON consumer is pain in the butt.

Just new kwarg `close=False` for `send` and `group_send` would do the work.

**Comment by andrewgodwin** [comment]
Pushed a `.close()` method instead as that means I don't need to override the two different kinds of send (JSON/non-JSON). It'll come out in the next release whenever I roll that.

**Comment by approxit** [comment]
Thanks for that! It will be handy! How about `group_close`?

In the meantime take your time and think about kwarg. It will be override of these functions, I know. But let me show you my point of view:

- With this fix in generic websocket class i need to send one message with farewell data and another message that closes connection. `close` kwarg in `send` is one message less when you want to attach some data while closing connection (like `You are kicked from the chat`). Sending farewell data message and then sending closing message separately will be tricky for guys without ordering anabled - cases with random disconnect without any announcement etc.
- `close` kwarg in `group_send` can be easily used with `Meeting ended by owner`. That would be a blast!
- It's last and only feature for websockets in generic classes that is missing. Write less, do more. Batteries included.
- It would be pretty, clean and DRY way to archive closing message with data with generic class.

Maybe someone will request it too, if you're not convinced enough. Anyways, thanks for fast reaction!

**Comment by andrewgodwin** [comment]
Messages to channels with a single client are always guaranteed to be in order, but sure, I'll add a close keyword argument into the sends too, it won't make things much messier.

**Comment by andrewgodwin** [comment]
This was done a while ago, forgot to close this!
