### ISSUE TITLE
Scheduled messages sent by server

### ISSUE THREAD

**Issue by albertored** [andrewgodwin/channels#245]
I need to create a webpage that shows the status of some application on server side.

For doing this I want clients to connect to server via websockets and the server pushing messages every n seconds on that websockets. This can be easily done using `celery` scheduled tasks. In particular I have a code similar to this
```python
@periodic_task(run_every=timedelta(seconds=5))
def send_status():
    Channel("status").send()
```
where the channel is associated with a consumer that collects the information from the system and sends them to the `Group`
```python
def ws_status(message):
    # collecting info...
    Group("status").send(collected_info)
```
This works pretty good. My problem is that collecting the status can be a little bit demanding and I don't want that piece of code being executed when no client is actually receiving those information. (It will happen often since it is a webpage built for being used by few users).

At the moment I solved this by setting a boolean variable and putting a check on it onto the `ws_status` consumer: if `False` information are not collected, if `True` they are collected, sent to the group and the variable is set to `False`. Then, at the client side, I have a script that sends an acknowledgement on receiving a new status, and a corresponding consumer on the server that set again the variable to `True` on receiving acknowledgment.

But I don't think this is a good solution, at the moment it works but maybe there are some caveats that I have not yet found.

**Comment by michaelkuty** [comment]
From my point of view is this issue similar to https://github.com/andrewgodwin/channels/issues/74

**Comment by albertored** [comment]
Yes, it is surely related to that issue but not equal.

Here the problem is not *how to run scheduled jobs* but *how to interrupt scheduled jobs if no one is listening*. Both using `celery` or `cron` the problem remains, there are situations in which it is useful to have a way of knowing if the Group is empty

**Comment by michaelkuty** [comment]
Yes i solving this using cache, i save all users and count to the cache because for me is not critical to have this persistent, you could easily handle ws connect and save all information which you needs, but maybe would be good to have native way for doing this

@andrewgodwin what you thinking about storing this information in channel backend ?

**Comment by andrewgodwin** [comment]
I would say this is actually #174 in that case (have a way to see if a group is empty or not), which I am still not totally okay making the channel backend deliver as a status, because it tightens the contract a little more.

Is there a reason you don't just want to leave it sending into the void? A Group.send() with no listening channels is basically free.

**Comment by michaelkuty** [comment]
I write simple code for handling group related data which now uses cache but is backend independent

    from .base import BaseManager

    users = BaseManager('mygroup', 'users')

    # on connect
    users.add_item(user)

    # on disconnect
    users.delete_item(user.id)

    users.get(user.id)
    users.count()
    users.all()


    class AdminsManager(BaseManager):

        scope = 'admins'


    admins = AdminsManager('mygroup')

    admins.add_item(user_admin)

    admins.all()

as you mention its extra calls on client connect

code lives here https://github.com/leonardo-modules/leonardo-channels/blob/feature/ws_frontend/leonardo_channels/managers/base.py

**Comment by andrewgodwin** [comment]
Feature requested for this was done.
