### ISSUE TITLE
websocket.disconnect: set Close status code somewhere in message

### ISSUE THREAD

**Issue by yassam** [andrewgodwin/channels#246]
I'd like to be able to tell if the browser closed a WebSocket connection by looking at the status code. I think maybe Chrome, if not other browsers, sets the Close Status to 1001, and it seems that Daphne defines a onClose function that receives "code" as a parameter, but it doesn't do anything with it:

https://github.com/andrewgodwin/daphne/blob/0.14.2/daphne/ws_protocol.py#L159

Is there a way of determining this already, or does it need to be added?

**Comment by andrewgodwin** [comment]
No, we'd need to add it into the ASGI spec. I think it makes sense - the WebSocket spec goes so far as to specify codes for "no close code" and "unexpected disconnection without a frame", so I think all bases are covered.

**Comment by andrewgodwin** [comment]
The spec and Daphne have now been updated to send this. It'll come out in the next Daphne release.
