### ISSUE TITLE
Web socket messages appended to model.objects and refreshing views

### ISSUE THREAD

**Issue by dsafaric** [andrewgodwin/channels#247]
Given an illustrative model Query:

```
class Query(models.Model):
    id = models.IntegerField(name="id", primary_key=True)
    query = models.CharField(name = 'query', max_length=1024)
```

I want to have my web application connected to a web socket server. When the web socket server receives a message, it should broadcast that message to a particular subset of socket connections established by the client.

The client (namely web browser), once receiving the broadcasted message, it should append it to Query.objects. From there on, the list of all queries should be automatically updated using Django templates and within it the defined model - without forcing the user to explicitly refresh it.

Hence, the questions of mine are: (I) using Channels (if this is the preferred way of dealing web socket connections in Django), how can I append the newly arrived Query object to Query.objects - without storing the object into the database because it has already been inserted prior sending to the web socket server, (II) refresh the content of the corresponding Django template/view.

**Comment by andrewgodwin** [comment]
I'm not entirely sure what you're trying to do here - you mention "request.objects", but WebSockets don't have a request. Could you not just listen for incoming websocket messages, create new Query objects when you receive those messages, and tie a post-save signal handler to send new Query objects out to browsers via a Group?

**Comment by dsafaric** [comment]
Sorry for the confusion - I meant Query.objects instead of request.objects (I updated the question). 

To clarify things, let me try to explain it by describing the entire flow:

1. a stream processing engine (namely Spark Streaming) is used for streaming data from a messaging system
2. upon retrieval of a message, the Driver of the stream engine asynchronously stored the messages into a PostgreSQL data store (the same as used by the Django models)
3. all messages that have been successfully stored, are then send to a WebSocket server (socket.io implementation)
4. the WebSocket server then broadcasts these messages to the corresponding channels - the channels are identified by an API key. 
5. then, the web app should receive these incoming messages, append them to the list of Query.objects (who's state was instantiated during page load and pre-populated with the data from the PostgreSQL data store). 
6. once the newly arriving messages are appended to Query.objects, the templates/views should update

**Comment by andrewgodwin** [comment]
Right, so it sounds like with Channels you would just need to replace steps 3 and 4, which you do like so:

3. All messages that are successfully stored are sent to a Group[s] with a known name

4. When WebSockets are connected they are added to the right Group (derived from the API key) and then get the right group sends from the previous step.
