### ISSUE TITLE
Member list in Group

### ISSUE THREAD

**Issue by logicnextPramod** [andrewgodwin/channels#249]
Hi,

I'm trying to build a chat system and following this example:
https://github.com/andrewgodwin/channels-examples/tree/master/multichat

Everything is working but I want to fetch the list of users in any Group(chat room)

Is there any way to do this with existing setup or I'm missing something?

Regards

**Comment by andrewgodwin** [comment]
You can only fetch the raw list of channel names with Channels directly, and there's no way to link that to users; if you wish to track which users are in the room, you'll need to implement your own model for that!
