### ISSUE TITLE
Daphne, twisted pip error when installing django channels

### ISSUE THREAD

**Issue by Copser** [andrewgodwin/channels#269]
I have a small problem with `pip` installing `django channels`, I noticed this from the *github* repository 

> Note: Recent versions of Channels also need recent versions of Daphne,
> asgi_redis and asgiref, so make sure you update all at once

I have neglected this and just started with `pip install channels`, but error occurred

`Could not find a version that satisfies the requirement twisted<16.3,>=15.5 (from daphne) (from versions: )
No matching distribution found for twisted<16.3,>=15.5 (from daphne)`

and when I try `pip install twisted`, it's just get confusing 

    Could not find a version that satisfies the requirement twisted (from versions: )
    No matching distribution found for twisted

So I have tried to find some solutions for this, and the solution suggest that I recompile my python, so I'm asking you is there any other solutions for resolving this issue.

I'm using `django==1.8.7` and `python3.5` for my existing project, I also have this question posted on [stackoverflow](http://stackoverflow.com/questions/38556363/daphne-twisted-pip-error-when-installing-django-channels).

**Comment by andrewgodwin** [comment]
It looks like Twisted only recently added Python 3.5 support to the setup.py information, so it won't publish to PyPI until the next release (16.4). In the meantime, you can: `pip install https://pypi.python.org/packages/18/85/eb7af503356e933061bf1220033c3a85bad0dbc5035dfd9a97f1e900dfcb/Twisted-16.2.0.tar.bz2#md5=8b35a88d5f1a4bfd762a008968fddabf`

(The bugs I read show that Python 3.5 has been passing tests for 10 months, they just didn't add the meta info yet)

**Comment by dkalejta** [comment]
I've spent a while trying to figure out why Twisted kept failing (at this point its at 16.6) to install. I forgot that I had Anaconda3 installed, and for some reason it was preventing the wheel from being built. Removing Anaconda allowed the installation to proceed without a hitch.

conda is kind of a tyrant it seems. Maybe I'm just a noob and don't know what I'm doing.
