### ISSUE TITLE
JsonWebsocketConsumer `receive` should have access to the `message`

### ISSUE THREAD

**Issue by poiati** [andrewgodwin/channels#270]
Hello, I think the interface bellow needs to get a reference to the message like the `receive` from the `WebsocketConsumer`. Without it we need to override the `raw_receive` to access the `message.user` for example.

```
def receive(self, content, **kwargs):
    ...
```

I'm not sure what is the optimal signature for this interface but just adding the message to `kwargs` seems good enough.

**Comment by andrewgodwin** [comment]
I would actually suggest `self.user` in this case, along with `channel_session`. I'll get on it soon.

**Comment by poiati** [comment]
Nice, I would like to work on that if you don't mind.

**Comment by andrewgodwin** [comment]
Please do! Add it into the non-JSON base class, then it'll be there for both variants.

**Comment by poiati** [comment]
@andrewgodwin, I'm really rethinking about this. I didn't know that we could access the message from the generic class instance and thus get the user from `self.message.user`. I think this is enough. Introducing the `self.user` shorthand is a bit overkill IMO. And being a bit purist It also kinda of violates the:

"There should be one— and preferably only one —obvious way to do it."

**Comment by andrewgodwin** [comment]
Agreed, you're probably right, if we start doing it there's sort of a precedent set with lots of special-case code. I'll close.
