### ISSUE TITLE
WebsocketDemultiplexer doesn't support UUID's

### ISSUE THREAD

**Issue by the-kid89** [andrewgodwin/channels#272]
Well playing with the new Data-binding functionality in channels I found that UUID's would cause encoding errors. After looking into it a bit I found that it was linked to https://github.com/andrewgodwin/channels/blob/master/channels/generic/websockets.py#L222.

I was able to fix the issue by making some very small changes to the code. I'll be posting my change soon.

**Comment by andrewgodwin** [comment]
Ah, yes, we used that encoder for the default serializer but I assume you're overriding that. Will take in the patch now.
