### ISSUE TITLE
Aerospike Support

### ISSUE THREAD

**Issue by hacknaked** [andrewgodwin/channels#278]
Would be great to have [Aerospike](http://www.aerospike.com/ ) backend for Django Channels.

**Comment by andrewgodwin** [comment]
It does not appear to have the right primitives for Channels (that is, a basic list type with atomic pop and set-and-check functionality), so I doubt we'll be able to support it; general databases are not going to perform well at Channels transportation unless they happen to have the right featureset.

**Comment by hacknaked** [comment]
What you mean? Aerospike provides[ ACID consistency](https://www.aerospike.com/docs/architecture/assets/AerospikeACIDSupport.pdf) in the presence of node failures and [support lists](http://www.aerospike.com/docs/guide/cdt-list.html). Am I missing something?

**Comment by andrewgodwin** [comment]
Ah, then it probably would, assuming list `pop()` is always ACID consistent and can be done in an efficient, blocking manner. Still, this would be outside the scope of the core Channels project - I'm happy to provide advice and help to someone trying to do it externally, though.
