### ISSUE TITLE
Message.reply_channel from models, views...

### ISSUE THREAD

**Issue by yaslim** [andrewgodwin/channels#287]
Hello,

_Firstly, thank you for Django Channels. I like very much this app and it helps me for my notifications system._

But I have a problem : I want add to a Group from models.py but I haven't access to channels.message.Message from this file.

Concretly, I want to do somothing like that : 

```
class Player : 
    ...
    def save(self, *args, **kwargs) :
         name_player = self.name
	 Group("player-"+name_player).add(message.reply_channel)
```

Logically, I have this error but I don't know how can I resolve it :

>  NameError: global name 'message' is not defined
         

Thank you

**Comment by andrewgodwin** [comment]
Well, you need to have the `reply_channel` around to add it to a group, and it's only available via a consumer, so you'll need to populate the group from a consumer.
