### ISSUE TITLE
WebsocketBinding ForeignKey help

### ISSUE THREAD

**Issue by xxxkilldogxxx** [andrewgodwin/channels#288]
Hi everybody,

In the examples for Websocket data binding there is only examples with non relation fields, however I would like to have some data from a foreign key relationship sent on create, update, delete etc.

Here is the current code which does not work, but this is how I would guess it should???

`class Bot(models.Model):

    TYPES = (
        ('PTC', 'PTC'),
        ('GOOGLE', 'GOOGLE')
    )

    # Bot credentials
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    type = models.CharField(max_length=100, choices=TYPES, default=TYPES[0])

    # Other
    initial_location = models.ForeignKey('map.Location', blank=True, null=True)
    pokestops = models.BooleanField(default=False)
    pokemon = models.BooleanField(default=False)
    speed = models.DecimalField(decimal_places=2, max_digits=10, default=27)
    min_cp = models.IntegerField(default=0)
    radius = models.DecimalField(default=100, decimal_places=2, max_digits=10)
    delay = models.IntegerField(default=5)

    def __str__(self):
        return '{}'.format(self.username)

class BotBinding(WebsocketBinding):

    model = Bot
    stream = "bot"
    fields = ['initial_location.lat', 'initial_location.long', 'initial_location.alt']

    def group_names(self, instance, action):
        return ["pokemon-updates"]

    def has_permission(self, user, action, pk):
        return True`

And here is the response I get back in the console.

`Got message {"payload": {"pk": 10, "action": "update", "model": "bot.bot", "data": {}}, "stream": "bot"}`

Is this supposed to happen or should I just be sending the foreign key ID then making a request on the front end to retrieve the related objects data via another stream?

Thanks for any help in advanced, I really respect this project and I love what it is bringing to the table.

**Comment by andrewgodwin** [comment]
You need to override the serialization methods to do more extensible serialising; this isn't in scope for Channels to provide, but you could plug something like Django REST Framework's serializers in.

**Comment by xxxkilldogxxx** [comment]
Thanks for the very fast response, I take it something like this is what you mean.

I didn't notice the note in the docs at first hence the question.


`class BotBinding(WebsocketBinding):

    model = Bot
    stream = "bot"
    fields = ['initial_location']

    def group_names(self, instance, action):
        return ["pokemon-updates"]

    def has_permission(self, user, action, pk):
        return True

    def serialize_data(self, instance):
        serial = BotSerializer(instance=instance)
        return serial`

**Comment by andrewgodwin** [comment]
Yes, that's the sort of thing I mean - the binding framework is designed so you can slot your own in, the one we supply is just a sort of basic default.

**Comment by xxxkilldogxxx** [comment]
I can understand that. Would you like me to make a PR with some examples of using DRF serializers?

Also I am having a issue I think related to https://github.com/andrewgodwin/channels/pull/260

`Traceback (most recent call last):
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\channels\management\commands\runserver.py", line 38, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\channels\asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\channels\asgi.py", line 48, in make_backend
    routing=routing,
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\channels\asgi.py", line 80, in __init__
    self.router = Router(self.routing)
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\channels\routing.py", line 25, in __init__
    self.root = Include(routing)
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\channels\routing.py", line 202, in __init__
    self.routing = Router.resolve_routing(routing)
  File "C:\Users\xXxKillDogxXx\pokemon\lib\site-packages\channels\routing.py", line 76, in resolve_routing
    raise ImproperlyConfigured("Cannot import channel routing %r: %s" % (routing, e))
django.core.exceptions.ImproperlyConfigured: Cannot import channel routing 'Pokemon_Go_Map.routing.channel_routing': type object 'BindingMetaclass' has no attribute 'register'`

I have bindings for each app inside its own bindings.py, I see the PR is ment to fix this issue but I am not sure how as I am still getting issues unless I am missing something?

**Comment by andrewgodwin** [comment]
A PR with some examples for the docs would be nice.

As for that stack trace, the fix was in master but not in a release. I just released `0.17.2` that should fix it.
