### ISSUE TITLE
quick question regarding django channels

### ISSUE THREAD

**Issue by mwaaas** [andrewgodwin/channels#291]
Hi would like to use django channel to my stack. at the moment am using haproxy infront of gunicorn. so I just scale by increasing the number of gunicorn containers. And when deploying there is zero downtime deployment since when one app server is down, the other haproxy is sending to the other gunicorn servers.

The question am asking using django channel. each web socket connection is connected to Daphne server. question is how to I run Daphne in a cluster , another question deploying code change in Daphne server means that it will close  the web_socket 

Or rather I don't understand how the web socket connection is being persisted in django-channel and the web_socket connection be load_balanced

Is it possible to add haproxy in front of interface servers and if yes which service will be responsible of maintaining the web socket connection haproxy or interface server.

**Comment by andrewgodwin** [comment]
Yes, you can just load-balance Daphne like you do Gunicorn. The design of channels means that it scales pretty horizontally in this scenario.

Balancing WebSockets is a little different to balancing HTTP requests, as they're long-lived - to take a Daphne server out of rotation means you'll kill sockets currently connected to it. However, channels is designed with Daphne separate from the worker servers for this reason; when you change application code, you only need to reload the worker servers, leaving Daphne instances alone (and with open connections). The only time to ever restart Daphne instances is when you're upgrading the version of Daphne you're running or changing redis settings that Channels is using.

**Comment by mwaaas** [comment]
@andrewgodwin  thanks for your feedback. one last question.

If I use haproxy to route traffic to Daphne. is the websocket connection maintained in haproxy of Daphne. what happens if I restart haproxy and don't restart Daphne, will the web connection still be alive. 

What am not getting is when a websocket request comes via haproxy its routed to the Daphne server. so that means if haproxy is restarted the socket will be restarted. am I right

**Comment by andrewgodwin** [comment]
Yes, you're right - an open WebSocket connection will be interrupted and closed if any part of the stack routing it at layer 7 is restarted (so HAProxy, Amazon ELB, Nginx, etc.)

**Comment by mwaaas** [comment]
cool, thanks now I understand. will write a blog once I have a sample project working.

django-channel and angular2 made in heaven.
