### ISSUE TITLE
Error when saving messages into datasore(models).

### ISSUE THREAD

**Issue by vinay13** [andrewgodwin/channels#294]
I followed the documentation and when i added models to save messages .

`def msg_consumer(message):`
  `  # Save to model`
    `room = message.content['room']`
 `   ChatMessage.objects.create(`
  `      room=room,`
  `      message=message.content['message'],`
    `)`
  `  # Broadcast to listening sockets`
  `  Group("chat-%s" % room).send({`
   `     "text": message.content['message'],`
  `  })`

`@channel_session`
`def ws_message(message):`
   ` # Stick the message onto the processing queue`
   ` Channel("chat-messages").send({`
      `  "room": channel_session['room'],  `
     `   "message": message['text'],`
   ` })`
 
then i am getting this error , 
error-  "room": channel_session['room'],
TypeError: 'function' object has no attribute '__getitem__'

but when i change the code to this , its working now.

`def msg_consumer(message):`
  `  # Save to model`
   ` room = message.content['room']`
  `  ChatMessage.objects.create(`
     `   room=room,`
     `  message=message.content['message'],`
   ` )`
   ` # Broadcast to listening sockets`
  `  Group("chat-%s" % room).send({`
      `  "text": message.content['message'],`
    `})`

`@channel_session`
`def ws_message(message):`
   ` # Stick the message onto the processing queue`
   ` Channel("chat-messages").send({`
        `"room": message.channel_session['room'],`
     `   "message": message['text'],`
   ` })`

> Is this a typo in docs or am  i missing something?

**Comment by ssteinerx** [comment]
Stick some back-ticks around that code -- it's not valid Python the way it is.

**Comment by vinay13** [comment]
(https://cloud.githubusercontent.com/assets/6693374/17600078/95b72e72-601f-11e6-9bd0-3c0a7aab3984.png)

**Comment by vinay13** [comment]
(https://cloud.githubusercontent.com/assets/6693374/17600124/c1885c4c-601f-11e6-994f-2712747b6491.png)

**Comment by andrewgodwin** [comment]
You need to refer to it as `message.channel_session`, not `channel_session` like you are, which is the decorator object.
