### ISSUE TITLE
Implement JWT Authentication

### ISSUE THREAD

**Issue by Skorpyon** [andrewgodwin/channels#300]
I use JWT authentication in my projects.

Can you suggest best way, how to implement it together with channels.
I spend a lot of time, but stuck, because websockets handshake don't support Autorization header.
Also it is strange use session cookies in mobile apps.
 
It will be great if you can advice how save Channels functionality (channel_session, message.user) with no cookies.
I see some ways: send JWT with JsonWebsocket payload or send it with GET params when connection `websocket.connect` created, parse it, build session key for catched user and save it.

And I have one quiestion more, is it enough to Authenticate user when websocket created or need authenticate him with each `receive` action.

**Comment by andrewgodwin** [comment]
You'll have to pass something across the WebSocket handshake - a custom Authorization header should work, but you'll have to manually extract it in a `websocket.connect` handler and save it into the `channel_session` (there are functions in `channels.auth` to help with this)

Once you have a user in `channel_session`, there's no need to reauthenticate in every `receive`; you can't, in fact, as you only get headers/GET params on `connect` handlers. Use the user from the `channel_session` - its whole purpose is to be a place to store stuff against an open socket.

**Comment by Dominionys** [comment]
@andrewgodwin @Skorpyon 
Hi, can you help me with Auth by token?

First, I send token with GET params. Then I extract it and save in channel_session.
Next time I try to get token from channel_session the parameter is lost

Consumer:
```
class MyConsumer(JsonWebsocketConsumer):
    channel_session = True
    strict_ordering = False
    slight_ordering = False

    def connection_groups(self, **kwargs):
        if not self.message.user.is_anonymous:
            return ["test"]
        return ["345"]

    def connect(self, message, **kwargs):
        print(message)
        pass

    def receive(self, content, **kwargs):
        serializer = ChatMessageSerializer(data=content)
        if serializer.is_valid(raise_exception=True):
            chat_message = serializer.save(author=self.message.user)
            text = JSONRenderer().render(ChatMessageSerializer(chat_message).data)
            self.send(content="{lol:lol}")

    def disconnect(self, message, **kwargs):
        pass

    def get_handler(self, *args, **kwargs):
        handler = super(MyConsumer, self).get_handler(*args, **kwargs)
        return token_request_parameter(handler)
```

Token_request_parameter:
```
def token_request_parameter(fund):

    @wraps(fund)
    def inner(message, *args, **kwargs):
        # Taken from channels.session.http_session
        try:
            if "method" not in message.content:
                message.content['method'] = "FAKE"
            request = AsgiRequest(message)
        except Exception as e:
            raise ValueError("Cannot parse HTTP message - are you sure this is a HTTP consumer? %s" % e)

        if message.channel.name == 'websocket.receive':
            return func(message, *args, **kwargs)

        token = request.GET.get("token", None)
        if token is None:
            _close_reply_channel(message)
            raise ValueError("Missing token request parameter. Closing channel.")

        try:
            token = Token.objects.select_related('user').get(key=token)
        except Token.DoesNotExist:
            raise exceptions.AuthenticationFailed(_('Invalid token.'))

        if not token.user.is_active:
            raise exceptions.AuthenticationFailed(_('User inactive or deleted.'))

        message.channel_session['user'] = token.user
        return func(message, *args, **kwargs)

    return inner
```

**Comment by raphael-boucher** [comment]
You can get some inspiration from here : http://www.machinalis.com/blog/jwt-django-channels/

**Comment by ZuSe** [comment]
Unfortunately the blog post is a bit outdated and uses django-auth-jwt.
I think there are many projects that depend on JWT these days, especially if you provide a REST-API for mobile clients it's highly recommended.
So instead of having a couple of hacky solutions wouldn't it be better to allow the use of already existing authentication backends for channels by setting it up in the config file?

**Comment by andrewgodwin** [comment]
Existing authentication backends don't map well onto Channels as they assume certain things about the flow, unfortunately. I'm sure someone could write code to map them over with some work, but I have other things I need to focus on.
