### ISSUE TITLE
Issue running Daphne and workers with supervisor

### ISSUE THREAD

**Issue by agustinaliagac** [andrewgodwin/channels#302]
Could someone provide an example of this?

I can run Daphne, but I'm having trouble launching a worker thread using supervisor.
Here's a code sample of supervisor.conf: 

[program:runworker]
command=python /home/django/environment/myproject/manage.py runworker
stopsignal=KILL
killasgroup=true

The browser waits a long time and then it shows:

> 503 Service Unavailable
Worker server failed to respond within time limit.

**Comment by andrewgodwin** [comment]
That looks correct to me. Have you verified that you're seeing output from runworker in the supervisor logs, and that you're not using the in-memory backend?

**Comment by agustinaliagac** [comment]
Thanks for answering this @andrewgodwin , I'm seeing output and it seems I'm using the Redis backend. I may add that if I run "python manage.py runworker" and then Daphne, it works perfectly. And Daphne doesn't seem to be the problem either. 

Here's the output of supervisor:

> 2016-08-17 19:01:09,439 INFO supervisord started with pid 3473
2016-08-17 19:01:10,441 INFO spawned: 'runworker' with pid 3477
2016-08-17 19:01:10,442 INFO spawned: 'daphne' with pid 3478
2016-08-17 19:01:11,421 DEBG 'daphne' stderr output:
2016-08-17 23:01:11,421 INFO     Starting server at 0.0.0.0:9000, channel layer laguardia.asgi:channel_layer

> 2016-08-17 19:01:11,519 INFO success: runworker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-08-17 19:01:11,519 INFO success: daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-08-17 19:01:11,591 DEBG 'runworker' stderr output:
2016-08-17 23:01:11,591 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)

> 2016-08-17 19:01:11,592 DEBG 'runworker' stderr output:
2016-08-17 23:01:11,592 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive

**Comment by andrewgodwin** [comment]
If it runs fine separately then there's not much I can do from my end to help it run - it looks like it's running just fine from your output. The only thing I can think of is mismatching configuration somewhere - did you run it manually using exactly the command you gave supervisor, from the same working directory?

**Comment by agustinaliagac** [comment]
Sorry for my delay in answering, I found the issue, but I haven't give it a final solution yet. When I run Daphne within Supervisor, it picks the wrong settings file, because it gets a wrong environment variable (DJANGO_SETTINGS_MODULE). If I run Daphne with the exact same command from bash directly, it works perfectly. I'm going to see if I can figure it out. Thanks for helping !

**Comment by andrewgodwin** [comment]
Ah, good to know - I'll let you figure out why! Thanks for coming back and saying what happened :)
