### ISSUE TITLE
Notify using web sockets from Views

### ISSUE THREAD

**Issue by rmad17** [andrewgodwin/channels#304]
I have a GET request coming in my views.py. Now I want to validate the data and pass the data to a channel for further running of a celery task from my views.py. When the task completes I want to send back real time result to the client. Is it possible?

**Comment by senden9** [comment]
I think for that you should call `channels.Group("groupname").send(some_msg)` at the end of your celery task. Then the client get a message if the task is finish. Of course the bowser/client must have a open websocket to your server for this.

**Comment by rmad17** [comment]
Thanks @senden9 will try this out.
