### ISSUE TITLE
Running two channel projects with same redis instance breaks- possible redis clash

### ISSUE THREAD

**Issue by antsmc2** [andrewgodwin/channels#312]
Hi,

I have two channel projects running on same server with same redis instance. On both, I configured similar redis settings on the CHANNEL_LAYER.

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
        "ROUTING": "MY_PROJECT.routing.channel_routing",
    },
}

When I try to access the second project, it erroneously takes me to the first project. After troubleshooting, I found the problem to be the redis url.  

What fixed the problem was to provide the redis URL string to a different db. I had to swap with this setting:
"CONFIG": {
            "hosts": ['redis://localhost:6379/10',],
        },

After this, requests got processed by the correct project.

**Comment by andrewgodwin** [comment]
Yes, if you configure two things with the same channel layer they will share it - that's a design feature.

You can also provide a different key prefix using the `prefix` configuration key if you don't want to use a different database.
