### ISSUE TITLE
How to make key word matching in routing work

### ISSUE THREAD

**Issue by cambridge0427** [andrewgodwin/channels#313]
In the channels-example, the chat example uses this kind of routing:
`route("chat.receive", chat_join, command="^join$"), `
`route("chat.receive", chat_leave, command="^leave$"),`
with an explanation saying " Handling different chat commands (websocket.receive is decoded and put onto this channel) - routed on the "command" attribute of the decoded message.")

I have trouble making this work on my own project. I dug into it a little bit. It seems the match method in routing.py tries to match the key words with the keys of the message received. However, the keys of a message are always path, text, order and reply_channel.  What I really need to match is the keys of "text".  It is a bug or I am using it in a wrong way?

Thanks a lot!

**Comment by andrewgodwin** [comment]
If you look closer in the chat example, you'll see that one consumer takes incoming WebSocket messages (that have the keys you mentioned), deserialises them, and puts the deserialised messages back on a new channel directly as their JSON bodies. The Demultiplexer also does this if you want another example.

To route like this, you _do_ need a consumer that unpacks the WebSocket format message first and puts the content onto the queue.

**Comment by cambridge0427** [comment]
Thank you!
