### ISSUE TITLE
HttpRequest._stream

### ISSUE THREAD

**Issue by ekmartin** [andrewgodwin/channels#32]
Django REST Framework (version 3.3.1) tries to access the `_stream` attribute on HttpRequests, which crashes with the following stack trace:

```python
Traceback (most recent call last):
  File "path/venv/lib/python3.5/site-packages/rest_framework/request.py", line 357, in __getattribute__
    return getattr(self._request, attr)
AttributeError: 'HttpRequest' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "path/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "path/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "path/venv/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "path/venv/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "path/venv/lib/python3.5/site-packages/rest_framework/generics.py", line 262, in patch
    return self.partial_update(request, *args, **kwargs)
  File "path/venv/lib/python3.5/site-packages/rest_framework/mixins.py", line 78, in partial_update
    return self.update(request, *args, **kwargs)
  File "path/venv/lib/python3.5/site-packages/rest_framework/mixins.py", line 68, in update
    serializer = self.get_serializer(instance, data=request.data, partial=partial)
  File "path/venv/lib/python3.5/site-packages/rest_framework/request.py", line 359, in __getattribute__
    six.reraise(info[0], info[1], info[2].tb_next)
  File "path/venv/lib/python3.5/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "path/venv/lib/python3.5/site-packages/rest_framework/request.py", line 183, in data
    self._load_data_and_files()
  File "path/venv/lib/python3.5/site-packages/rest_framework/request.py", line 243, in _load_data_and_files
    self._data, self._files = self._parse()
  File "path/venv/lib/python3.5/site-packages/rest_framework/request.py", line 289, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
  File "path/venv/lib/python3.5/site-packages/djangorestframework_camel_case/parser.py", line 15, in parse
    data = stream.read().decode(encoding)
  File "path/venv/lib/python3.5/site-packages/django/http/request.py", line 293, in read
    return self._stream.read(*args, **kwargs)
AttributeError: 'HttpRequest' object has no attribute '_stream'
```

**Comment by nikolatech** [comment]
Even im running into this issue when the websocket is used

**Comment by vikrantpogula** [comment]
Even i run into the same issue when using rest framework along with the websocket

**Comment by andrewgodwin** [comment]
Yeah, I'm looking into an emulation layer to prevent this; hopefully I can provide a StringIO object with the right information for DRF.

**Comment by vikrantpogula** [comment]
@andrewgodwin Hey, any update on this ? I'd be happy to help in anyway if there's  something I can do !

**Comment by andrewgodwin** [comment]
Well, I just finished finalising how to transmit request bodies in ASGI, which was the underlying blocker - there's no way to provide the body emulation otherwise. Now that's done, fixing up the Request object to actually take those bodies is next, followed by things like this that are emulation layers.

You can take a stab if you like, but I have it half-written already, just need to get it done and tested :) What would be useful is if you could work out what DRF is trying to use _stream for; I'd like to make sure it's just trying to access the raw request body.

**Comment by vikrantpogula** [comment]
@andrewgodwin OK! Ive just read the ASGI spec and understand what you exactly mean. I will take a stab into DR..

**Comment by vikrantpogula** [comment]
@andrewgodwin i've been playing around with channels last couple of days, really great work, thanks !

regarding the `_stream` the issue does not exist when using separate servers (ie not using `--accept-all`) for HTTP and WS. Everything seems to work as intended.

PS : I've seen you have change the current (`0.8`) approach and are now using `daphne` as the server. :+1:

**Comment by andrewgodwin** [comment]
Yup - running WSGI and WS seperately will always be an option, as WSGI is just more mature and stable and it's silly not letting you use it (and likely slightly more efficient as it's not double-transforming requests).

Only downside is that it means no simultaneous websocket support - you have to tell your webserver to route a prefix - but that's not the worst thing. I'll be adding some diagrams into the real docs about this to show the different options.

**Comment by vikrantpogula** [comment]
@andrewgodwin just posting an update here. I was previously wrong, everything is not working as intended, but I have better info:
- DRF tries to access `_stream` while trying to parse request bodies (POST/DELETE requests)
- Even if the request does have a body - error is not raised till you access `request.data`

TL:DR from my testing (`v0.8`)
```
Works
  - request.META
  - headers
  - query_params

Doesn't Work
 - request.data
```

**Comment by andrewgodwin** [comment]
Yes, I suspect that I need to implement `read()` and other methods on the new WsgiRequest class.

**Comment by DanLipsitt** [comment]
Is it possible to implement this as a patch against v0.8, or does it have to wait for ASGI to settle down? I'm trying to use channels with DRF right now. 

I'll take a look and try to at least develop a failing test. I don't know if I'll be able to do more than that, or if it makes sense to.

**Comment by DanLipsitt** [comment]
Do you have a sense of when that might be? Not trying to push. :wink:

**Comment by andrewgodwin** [comment]
Afraid I can't commit to dates; I'm not working on this in a paid capacity yet, so it's all personal time as and when it comes up.

**Comment by DanLipsitt** [comment]
A comment on `django.http.request.HttpRequest.read()` says

```
# File-like and iterator interface.
#
# Expects self._stream to be set to an appropriate source of bytes by
# a corresponding request subclass (e.g. WSGIRequest).
# Also when request data has already been read by request.POST or
# request.body, self._stream points to a BytesIO instance
# containing that data.
```

It looks to me like setting `self._stream = BytesIO(self._body)` in `AsgiRequest.__init__()` might satisfy that?

**Comment by andrewgodwin** [comment]
Yup, that's the plan. Just need to make sure the whole thing works end-to-end properly and correctly encodes/decodes; it's all still slightly experimental.

**Comment by andrewgodwin** [comment]
OK, stream is now implemented.
