### ISSUE TITLE
Unable to receive data from websocket

### ISSUE THREAD

**Issue by raphael-boucher** [andrewgodwin/channels#331]
I'm having troubles receiving a message through websocket. The socket connection is established (`WebSocket CONNECT /ws [127.0.0.1:49352]`), but I don't receive any of the data sent. Here is my setup :

```python
# routing.py
def ws_message(message):
    print(message.content['text'])
    message.reply_channel.send({
        "text": message.content['text'],
    })

channel_routing = [
    route("websocket.receive", ws_message, path=r'^/ws$'),
]
```

I'm using the same channels version than channels-example (0.17.2), and this simple config works on this example project.

My settings are basically the same :

```python
# settings.py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)],
        },
        "ROUTING": "myproject.channels.routing.channel_routing",
    },
}
```

Any idea where this could come from, or where to dig? I'm pulling my hair out!

PS: thanks for this project, it looks very promising!

**Comment by andrewgodwin** [comment]
So, a couple of things to run down:

* What version of channels, daphne, and Twisted are you running? There was a bug in Twisted for a while that looked just like this that the more recent release of Daphne fixed
* Does the print you have print to the console?
* Do you see anything in your browser's network inspector tab?

**Comment by raphael-boucher** [comment]
```
daphne==0.13.1
Twisted==16.4.0
channels==0.17.2
```

The print does not print anything (i have tried breakpoints).
In chrome, I can see the frame sent.
I can hook successfully on the `websocket.connect` event.

**Comment by raphael-boucher** [comment]
It works with daphne 15, thanks a lot!
I had the version pinned by mistake in my requirements.

**Comment by andrewgodwin** [comment]
No problem, glad it was an easy fix! That Twisted/Daphne bug was nasty, things just vanished without a trace (as you saw).
