### ISSUE TITLE
getting this error while saving to the db. AssertionError: Group name not valid

### ISSUE THREAD

**Issue by mwaaas** [andrewgodwin/channels#332]
Here is the stack trace am getting.

web_worker_1  |     return func(*args, **kwargs)
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
web_worker_1  |     self.save_model(request, new_object, form, not add)
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1007, in save_model
web_worker_1  |     obj.save()
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
web_worker_1  |     force_update=force_update, update_fields=update_fields)
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 833, in save_base
web_worker_1  |     update_fields=update_fields, raw=raw, using=using)
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
web_worker_1  |     response = receiver(signal=self, sender=sender, **named)
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/channels/binding/base.py", line 97, in save_receiver
web_worker_1  |     cls.trigger_outbound(instance, "create" if created else "update")
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/channels/binding/base.py", line 127, in trigger_outbound
web_worker_1  |     group.send(message)
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/channels/channel.py", line 72, in send
web_worker_1  |     self.channel_layer.send_group(self.name, content)
web_worker_1  |   File "/usr/local/lib/python2.7/site-packages/asgi_redis/core.py", line 217, in send_group
web_worker_1  |     assert self.valid_group_name(group), "Group name not valid"
web_worker_1  | AssertionError: Group name not valid

**Comment by senden9** [comment]
And what group name do you try to use? According to [the source](https://github.com/andrewgodwin/asgiref/blob/a2d93b7a3356581ae77441818503d04ade23184b/asgiref/base_layer.py#L97-L102) your groupname is longer that 100 characters or it isn't a string.

**Comment by bastbnl** [comment]
I believe I managed to get the same (or at least very similar) error when using a channel name containing the @ character

**Comment by andrewgodwin** [comment]
Your group name must also be a Unicode string, not a bytestring, that's a common mistake. Closing unless  we get confirmation it's not just an invalid group name (but opening another ticket for better error messages)

**Comment by mwaaas** [comment]
got the error my group name had "@" which is not a valid character.
