### ISSUE TITLE
LiveServerThread with channels

### ISSUE THREAD

**Issue by Korijn** [andrewgodwin/channels#338]
The testing utility `django.test.testcases.LiveServerThread` is a fantastic tool for functional testing (with e.g. `selenium` or `requests`). You start a threaded server with an isolated test db and you can run your test on it. This even supports parallel testing with multiple threads on their own ports and separate databases. Projects like pytest-django make this super-easy, by providing [a `live_server` fixture](https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/fixtures.py#L268) that your test can depend on.

This doesn't work when you use channels however! Are there any plans to extend the LiveServerThread to support channels as well?

**Comment by andrewgodwin** [comment]
There are no plans, but it could be done in theory. I'll mark this as one of our "maybe" issues if someone is interested.

**Comment by Korijn** [comment]
Would you agree if I said that I think the code in the channels runserver management command should be referred to as an example?

**Comment by andrewgodwin** [comment]
That is certainly the base to build upon - I don't know how much change would be needed as I haven't had a chance to look at the live server thread code yet (I'm on a phone).

**Comment by Korijn** [comment]
Okay. Well, I'm considering to do it myself, but I want to get a feel for the work required before I start. It would be very helpful if you could share your thoughts, if you can spare the time for it. :)

To me it looks like I might also need to draw some inspiration from Django's runserver and testserver commands, aside of the LiveServerThread class and channels' runserver command which I already mentioned earlier. I can write the pytest-django fixture separately later.

**Comment by andrewgodwin** [comment]
Looking at it, you should be able to do the same thing as runserver - launch a Daphne server where the current code launches its own server, and then shut it down afterwards. You'll need to do it in a subthread because of the Twisted event loop, but that's already what happens in that class.

**Comment by Korijn** [comment]
Awesome, thanks for the explanation. I can get started. You might see a PR from me sooner than later!

**Comment by ekondrashev** [comment]
@Korijn Do you have any progress here? Was the PR already merged? Maybe some in-the-middle solution?

**Comment by ekondrashev** [comment]
@andrewgodwin could you please provide any code example available on how to start Daphne server manually, registering consumers defined in the projects?

**Comment by Korijn** [comment]
This will become a priority somewhere in november for our team, so you can expect some news by then.

**Comment by ekondrashev** [comment]
@Korijn thank you, it will help a lot if you can share some developments if any. It should be pretty easy to implement the subj, imo.
Could you please let me know if making use of
`from channels.tests import ChannelTestCase`
is something that looks reasonable to enable channels in scope of some functional selenium-based test?

**Comment by andrewgodwin** [comment]
@ekondrashev There are examples in the docs - the consumers aren't in Daphne, you start a copy of Daphne (just pointing at a channel layer) and then workers which are where the consumers live.
