### ISSUE TITLE
Running multiple instances with same redis backend

### ISSUE THREAD

**Issue by JanMalte** [andrewgodwin/channels#341]
Is it possible to use the same redis database for multiple instances of Django + Channels on the same machine?

`settings.py`
```python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'ROUTING': 'project.routing.channel_routing',
        'CONFIG': {
            'hosts': [
                ('localhost', 6379)
            ],
        },
    },
}
```

**Comment by bastbnl** [comment]
I do believe so. I'm using this:
        'CONFIG': {
            'hosts': [
                'redis://127.0.0.1:6379/1',
            ],
        }

I'm using channels and celery in the same project and I understood the "path" (/1) designates the redis database. Celery is using /0 in my project.

**Comment by JanMalte** [comment]
Thanks for this hint. Would be still interesting, if there is any conflict between multiple instances in the same redis database.
We are running multiple instances on the same machine and therefor try to use a single redis database part for each django app instance.

**Comment by andrewgodwin** [comment]
It's perfectly fine - either do as above and use database numbers, or use a different `prefix` in the configuration (the default is `asgi`) per channel layer cluster.

**Comment by PunkFleet** [comment]
> I do believe so. I'm using this:
> 
> ```
>         'CONFIG': {
>             'hosts': [
>                 'redis://127.0.0.1:6379/1',
>             ],
>         }
> ```
> 
> I'm using channels and celery in the same project and I understood the "path" (/1) designates the redis database. Celery is using /0 in my project.

Can you show a case how configure redis for channels and celery both?
I have a wrong using this config:
```
# Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# ASGI and Channels
ASGI_APPLICATION = "main.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [('redis://localhost:6379/2')],
        },
    },
}
```
