### ISSUE TITLE
redis:// URL host & port configuration

### ISSUE THREAD

**Issue by johnfraney** [andrewgodwin/channels#39]
A `redis://` URL is a great shorthand for redis hostname & port settings, and it can easily be stored in an environment variable. It's very handy for Docker/Dokku deployments and is used in other Django + redis libraries ([Celery](http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#broker-redis), [django-redis](https://github.com/niwinz/django-redis))

Rather than:
```
...
        "HOSTS": [("redis-channel-1", 6379), ("redis-channel-2", 6379)],
...
```
It would look like this:

```
...
        "HOSTS": ["redis://redis-channel-1:6379/0", "redis://redis-channel-2:6379/0"],
...
```

**Comment by andrewgodwin** [comment]
Yes, this might be a good idea. I was trying to standardise the format of HOSTS across other potential backends, but there aren't any others with host support yet.

Might just be worth having both supported, they're easy to distinguish programmatically.

**Comment by johnfraney** [comment]
Choice is always good! The current (host, port) tuple is sensible. The `redis://` support would be nice, though, especially in deployment scenarios that provide a `redis://` URL (like [dokku-redis](https://github.com/dokku/dokku-redis)).

**Comment by bastianh** [comment]
I think it's at least important to be able to add the database number for the redis server, since people might host more then one django app on the same server.

**Comment by andrewgodwin** [comment]
Did antirez back down on his plan to drop the database numbers?

**Comment by bastianh** [comment]
database numbers are only deprecated for redis-cluster. Alternatively some kind of namespacing the keys would be possible ?

**Comment by andrewgodwin** [comment]
There's already a "PREFIX" setting that can be configured for the backend, it's just not documented yet.
