### ISSUE TITLE
Preferred location for discussion about django-channels  

### ISSUE THREAD

**Issue by techdragon** [andrewgodwin/channels#43]
After the initial discussion on django-developers, and with django-channels progressing but not yet in django itself. Is there a preferred location for discussing django-channels or since the plan is to move django-channels into django itself, should the discussion just take place in django-developers?

**Comment by nemesisdesign** [comment]
IMHO best to discuss in django-developers; all the parties involved are already following there, moving the discussion somewhere else can potentially leave out people who are interested but do not realize the discussion is moving.

Also it seems this work is well supported by many django core devs and the DSF itself, so it makes perfect sense to discuss it on django-developers to me.

**Comment by andrewgodwin** [comment]
Yup, django-developers is the place for general discussion; any email with the word "channels" in it that goes there lands straight in my main inbox. I also started up #django-channels on IRC if people wanted to use that, but it's empty right now, so not sure if it's sensible.
