### ISSUE TITLE
With channels, runserver is not longer using WSGIRequest

### ISSUE THREAD

**Issue by bastianh** [andrewgodwin/channels#51]
Hi,

in one of my projects I'm using a middleware that changes the request to allow easy url routing from javascript.
Unfortunately it requires request.environ, which is part of WSGIRequest but not part of HttpRequest. (https://github.com/django/django/blob/master/django/core/handlers/wsgi.py#L80)

Is it possible to still use WSGIRequest in the patched runserver ?

Bastian

**Comment by andrewgodwin** [comment]
Well, request.environ is not part of the public Request API so I was trying not to provide it (for example, a test client request isn't a WSGIRequest either). Why do you need it? All the things it provides appear in META, pretty much.

**Comment by bastianh** [comment]
The library I'm using is using it, I guess it's also possible to change that or use my own but I wasn't sure if that's the only difference.

https://github.com/jrief/django-angular/blob/master/djangular/middleware.py

**Comment by andrewgodwin** [comment]
Yeah, that library is using undocumented features; they're manually rebuilding requests, which just isn't going to integrate with Channels very well. There's not much I can do to support that yet, really; hopefully once we have a clear outline of how requests will differ in a non-WSGI environment I can contribute pull requests to projects like these to help them use things via documented APIs.

For what it's worth, I don't know why they don't mutate the Request object on the fly like other middlewares do, but there might be a good reason for it.

**Comment by knbk** [comment]
`request.META` is the same dict (not just a copy, but the same object) as `request.environ`. Any app that uses `request.environ` can switch to `request.META` without any issues.

**Comment by andrewgodwin** [comment]
Right; there's no need for .environ at all, from what I understand.
