### ISSUE TITLE
patched runserver cutting query parameters from HttpRequest.build_absolute_uri()

### ISSUE THREAD

**Issue by bastianh** [andrewgodwin/channels#53]
I noticed that oauth login was not working with the modified runserver because `HttpRequest.build_absolute_uri(location)` (https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.build_absolute_uri) cuts all query parameters.

when the expected result ist `http://localhost:9000/api/callback/?code=Z7VNafOdj5oYuri2yD1OvKH&state=zEpKuXdqldmo` with the modifed runserver it's only `http://localhost:9000/api/callback/`

**Comment by andrewgodwin** [comment]
New runserver/daphne code fixes this.
