### ISSUE TITLE
How to write "broadcaster" for a different/custom protocol

### ISSUE THREAD

**Issue by owais** [andrewgodwin/channels#57]
Just curious if channels provides a way to write a custom router/broadcaster that can accept/listen to some protocol other than http and websockets?

**Comment by andrewgodwin** [comment]
Yup - it'll be easy to write a new custom one, and I'm writing up a formal spec and example code at the moment to make it even easier. Basically, all you'll need to interact with are a couple of callables on a channel layer class (one for send, one for receive) and figure out an encoding, then just transport data to and from the socket.

**Comment by owais** [comment]
Awesome!
