### ISSUE TITLE
How can I send message from views ?

### ISSUE THREAD

**Issue by rajasimon** [andrewgodwin/channels#59]
I'm very new. I like to fire message from view. How to do that ? 

After finishing <code>[Running with Channels](http://channels.readthedocs.org/en/latest/getting-started.html#running-with-channels)</code> I checked with javascript <code>socket.send("hello world")</code> and its working but what I want is using python how to send ? 

i.e) 

    def bot_submit(request):
        bot_result =  request.POST
        # I need bot_result content on frontend how to do that ?
        return HttpResponse('ok')

**Comment by andrewgodwin** [comment]
Well, you need to know the response channel you're sending to - if you're sending from a WebSocket you'll have that as the `reply_channel` value of the message in the ``websocket.receive`` handler.

Here though, you have a HTTP post, so I'm not sure what you're trying to do - you could just return the value in the response?

**Comment by rajasimon** [comment]
Thanks for the replay.. Ya the response channel is <code>chat</code> only and I tried 

    def result_submit(request):
        result = {}
        result['World'] = 'Earth'
        Group("chat").send(content=result)
        return HttpResponse('Ok')

And It's throwing below error...

<code>exceptions.TypeError: serverSend() takes at least 2 arguments (1 given)</code>

**Comment by andrewgodwin** [comment]
Ah, you're using a Group, that makes more sense (otherwise you'd need to get the individual response channels across to the view). 

Group.send() takes a dict, not keyword arguments, though I'm not sure why you don't get the error it's meant to throw immediately - can you paste the full traceback?

**Comment by rajasimon** [comment]
Oh! Not keyword arguments make sense... And currently I having this code and It's working 

    result = {}
    result['content'] = 'This is another message'
    Group("chat").send(result)

**Comment by lawrence-gandhar** [comment]
Hi, can anyone help me to send the message from a view in django to the channels. I am using the following in views. I am a beginner in channels. Help is appreciated.

`message = {}`
`Channel('background-hello').send(message)`

**Comment by proofit404** [comment]
@lawrence-gandhar Please use Django users mailing list for further questions with the topic about usage.

To solve your current issue please try following:

```python
Channel('background-hello').send(message, immediately=True)
```
