### ISSUE TITLE
seperating locking and messages backend?

### ISSUE THREAD

**Issue by bastianh** [andrewgodwin/channels#62]
I wonder if it makes sense to seperate the locking and messages backend. I think if you would want to use rabbitmq for example for messages you might still want to use redis or memcache for locking?

**Comment by andrewgodwin** [comment]
Yes, I've already removed locking from the ASGI spec; I'm going to try and implement it directly on the sessions backend for starters.

**Comment by andrewgodwin** [comment]
Locking is now gone completely, and replaced with `enforce_ordering`, which uses sessions.
