### ISSUE TITLE
DatabaseChannelBackend is broken

### ISSUE THREAD

**Issue by DanLipsitt** [andrewgodwin/channels#69]
In the master branch, `channels.backends.database.DatabaseChannelBackend` inherits from `BaseChannelBackend`, which appears not to exist anymore.

**Comment by andrewgodwin** [comment]
Yup, it needs rewriting.

**Comment by andrewgodwin** [comment]
Fixed by a9810014caaf357d75545d1d7ebbaf88f2341307, it now sits standalone, and is moved to `channels.database_layer`.
