### ISSUE TITLE
Running the chat tutorial does not seem to work

### ISSUE THREAD

**Issue by ami-fairfly** [andrewgodwin/channels#72]
Hey,

I have a local Redis server running and the following configurations - trying to follow the chat tutorial

settings.py:
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "App.routing.channel_routing",
    },
}
```

routing.py
```
channel_routing = {
    "websocket.connect": ws_connect,
    "websocket.receive": ws_message,
    "websocket.disconnect": ws_disconnect,
}
```

and the consumer.py is identical to the tutorial code in http://channels.readthedocs.org/en/latest/getting-started.html#persisting-data

connecting seems to work fine, I see redis being updated etc. but when trying to send a message - this line will run but no message will be received by the client
`Group("chat-%s" % message.channel_session['room']).send(message.content)`

I am connecting to `ws://localhost:8000/lmao`

Any idea why or how I can troubleshoot it?

**Comment by andrewgodwin** [comment]
Have you updated to asgi_redis 0.8.2? I just released it and it should fix an issue where the new Daphne code wasn't getting any messages.

**Comment by ami-fairfly** [comment]
@andrewgodwin Again, that was fast :)

It's not on PyPi though https://pypi.python.org/pypi/asgi_redis

**Comment by andrewgodwin** [comment]
Oh, my bad. I need to automate releases more. Should be there now.

**Comment by ami-fairfly** [comment]
Thanks, works now! Fastest fix ever.

@andrewgodwin Without trying to be pushy or anything, would you say Channels+Redis is close to being ready for production? :)

**Comment by andrewgodwin** [comment]
Yes, I think so - there's one major feature that needs doing (linearization) and then I want to get some load and stability testing in before I release a 1.0 and start a Django patch. The API is certainly mostly stable now.
