### ISSUE TITLE
Consistent hashing and "prefetch count" 

### ISSUE THREAD

**Issue by erikash** [andrewgodwin/channels#75]
Hi, 
I've played around with channels a few weeks back, but I can see that a lot have changed since then  :-)

I have a use case in which I must assure that only a single command is executed per account at a given time. 

Can I leverage the response channels (!account1,!account2), in a way that the matching workers will process them one at a time and in orders? 

Will this use case be addressed as a part of the channels framework? 

Best, 
Erik.

**Comment by andrewgodwin** [comment]
This isn't something natively built into channels - response channels won't get listened to by workers in the way you intend (and you have reminded me I should make them unroutable); they'll just get multiple listeners anyway.

If you want to do this, you need to either:
* Use your own custom messages with an incrementing `order` key and the `global_ordering` decorator in ``strict`` mode with a custom reply channel that matches a username
* Manually keep track of the lock state using a datastore
* Don't use channels for this and use something else

Channels is generally designed for shared-nothing processing, so it's not natively suited to the idea of "one command per user" - by asking for that, you suddenly require that the whole system knows about the rest of it, which is great for processing but awful for performance. This is one of the things, like retrying tasks, that I expect to be built on top of it as an opt-in thing for people.

**Comment by erikash** [comment]
Thanks for the elaborate answer! 

Regarding the first option, can I use a different order key per "account"?

**Comment by erikash** [comment]
Or better terminology would be account revision...

**Comment by andrewgodwin** [comment]
Order is enforced strictly on the value of `reply_channel`, so match that up as you like.

**Comment by andrewgodwin** [comment]
Be aware, though, that channels is non-guaranteed delivery - there's a chance that one of your messages won't get through at all (very small, but you need to prepare for it). If you absolutely need guaranteed, in-order, exactly-once processing, channels is not the task queue you need.

**Comment by erikash** [comment]
Great thanks!
