### ISSUE TITLE
Is not clear how to hookup Django's URL routing to the channel routing, or if it even possible?

### ISSUE THREAD

**Issue by mandx** [andrewgodwin/channels#92]
While it is not that complicated to write routes for the `CHANNEL_LAYERS['ROUTING']` setting, the Django Admin and some 3rd party apps (like Django Rest Framework) generate routes to be included into a URLConf.

Is it possible to just hook up Django's URL resolving system into Channel's routing system? Like:
```python

channel_routing = {
    'http.request': DjangoURLConfConsumer(),

    # Websocket stuff:
    'websocket.connect': consumers.ws_connect,
    'websocket.receive': consumers.ws_receive,
    'websocket.disconnect': consumers.ws_disconnect,
}
```
where `DjangoURLConfConsumer` is a function/class that would load Django's URLConf and dispatch the message to the traditional (as in synchronous) views.

Maybe Channels already does this?

**Comment by andrewgodwin** [comment]
Yes, you can use the `channels.handler.ViewConsumer` to pass any `http.request` message into the view system, though this is done for you by default.

In addition, in the latest master code, the routing gains the ability to route to custom HTTP endpoints/WebSocket consumers based on url (`path`), and will always fall back to Django's view handling if nothing processes a `http.request` message.

**Comment by andrewgodwin** [comment]
(Generally, you don't want to route `http.request` in the routing and just leave it out so it does the default, which is exactly what you want. You only need to route it yourself if you're doing something unusually low-level)

**Comment by mandx** [comment]
Got it, thanks! I just didn't find the docs section stating that this already happens by default. Thanks for the quick reply!

**Comment by ThaJay** [comment]
> Got it, thanks! I just didn't find the docs section stating that this already happens by default. Thanks for the quick reply!

Channels is looking really good this far. Perhaps explicitly add this to the starting section of the docs? I did not find it either so had to come here to find this out.

**Comment by andrewgodwin** [comment]
Good point, I thought I had. Added a paragraph in there.

**Comment by JustinTTL** [comment]
I was just trying to integrate channels into an existing django/DRF project and I have been running into an issue where my original urls paths are breaking. My root index view leads to 301 infinite redirects loop and my other views like `/rfs/` results in a 404.

The app works when I remove "channels" from `installed_apps`

I am using django auth backend with `login_required` for all my views.

I am fairly new to django and would love some help on this!

## my_app/urls.py 
```python 
urlpatterns = [
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    url(r'^.*', index, name='index'),
]
```
## my_app/routing.py
```python 
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
from django.urls import path

from api.consumer import EchoConsumer

application = ProtocolTypeRouter({
    'websocket': AuthMiddlewareStack(
            URLRouter([
                path('', EchoConsumer)
            ])
    )
})
```

## Settings
```python
# Application definition
INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django_extensions',
    'rest_framework',
    'rfs.apps.RfsConfig',
    'api.apps.ApiConfig',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```
## Versions
```
channels==2.1.1
daphne==2.1.2
```

**Comment by itsmehdi97** [comment]
Is it possible to process some of http requests by channels http protocol and some of them by the traditional django views based on their url?
I thought this issue is related to my question but I couldn't find the `channels.handler.ViewConsumer` you mentioned [here](https://github.com/django/channels/issues/92#issuecomment-199038536) .

**Comment by carltongibson** [comment]
@itsmehdi97 Take a look at the example here: https://channels.readthedocs.io/en/stable/topics/routing.html#urlrouter
It covers the exact use-case you're asking about.
